### ISSUE TITLE
MSM estimator for joining adaptive trajectories

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#1044]
No bug report. Just a discussion.

What is your opinion on making an estimator that understands that adaptive trajectories are spawned from previous ones and treat them as long trajectories during estimation by stitching them together?
This would allow us to use very large lag times for MSMs and also obtain more statistics from the simulations.

i.e., traj2, traj3 both branch off from traj1 at the same frame. Then traj4 branches off from traj3.
```

traj1 .................____
               traj2   |_____________
               traj3   |.....................___
                                     traj4   |........................
```
So traj4 could be joined to the dotted part of traj3 and traj1 to make a "long" trajectory.

This cannot really be done efficiently in a previous step because adaptive trajectories can branch from a single frame into multiple new trajectories so joining them beforehand we would be making lots of copies of the same trajectory wasting (memory/disk) space.

**Comment by marscher** [comment]
This can be achieved by grouping the trajectories which belong together 
in a tuple. These grouped trajs will be treated as single 
realization/trajectory in subsequent estimation. Is this what you desire?

**Comment by stefdoerr** [comment]
Hm not exactly because as you can see in the example once you branch off to a new adaptive trajectory you need to disregard the rest of the trajectory for the purposes of the joined longer one. You can still use the whole trajectory independently.

We would need some kind of index pointing to the "parent" trajectory/frame combination for each trajectory, since each trajectory can have multiple children spawned from different frames.

**Comment by fabian-paul** [comment]
This an interesting suggestion. It reminds me a bit of the *weighted ensemble* technique. Maybe we should have a look into the weighted ensemble literature. 

Knowing explicitly which trajectories branch from which other trajectories might also help in checking the connectivity/ergodicity of the sampling. Because if we known that a trajectory branches off another one, we know with certainty that it is connected to it. In contrast, if we didn't have this information, the connectivity could always be spurious, because of projection error. So this information could help to narrow down connectivity problems as it allows us to focus on the true disconnected trajectories and ignore everything where we can be sure that's connected.

This might also be interesting in combination with core set MSMs as it allows to follow the trajectories into the past and into the future across restarts/branches, though there might be some theoretical questions that have to be answered first.

**Comment by nsplattner** [comment]
Are you taking velocities+positions from each frame for the restart or only positions? In the case of taking only the positions, the trajectories are not really continuous and should not be treated as one trajectory. Having the information from which frame a trajectory starts is potentially interesting, but I think we first have to define the potential usecases and what sampling methods would be used to create the trajectories.

**Comment by stefdoerr** [comment]
Yes Nuria you are right. We don't restart with the velocities because we don't store them on GPUGRID but I could add an easy fix to the adaptive to use velocities if present which is the case for local/cluster simulations.

In our implementation of adaptive we keep track of simulation "lineage" by the trajectory (folder) names. It's an arbitrary naming scheme obviously: `e5s7_e3s1f15p1` means that this simulation (e5s7) is the 7th simulation of epoch 5 and it originates from simulation (e3s1) so sim 1 of epoch 3 and specifically from it's 15th frame of it's 1st piece (just in case you have multi-piece trajectories like we do on GPUGRID).

I have a `reconstructAdaptiveTraj` function which actually does this joining but I would not use it to estimate an MSM because it would be a waste of resources as I mentioned to join every single path in the lineage tree into a new trajectory.

Easiest use case I see would be doing adaptive with i.e. 1ns trajectories and then being able to build a model with 20ns lag time which will be more probable to converge.

**Comment by franknoe** [comment]
I think this is a very useful idea, but seems to be a level above PyEMMA. As Nuria pointed out, you need to know something about how trajectories were restarted and which protocol was used in order to join in a meaningful way. An adaptive sampling framework would be the right place to do this - so I would presently do this in HTMD rather than PyEMMA, but perhaps we can come up with a joint framework for that part of the work in the future.

**Comment by stefdoerr** [comment]
Yeah you have a point in that. I guess if I find some time I could subclass your estimators and modify them to work with explicit knowledge of our adaptive scheme.
Thanks for the input!
