### ISSUE TITLE
print warning/change chunksize for io efficient covariance computation

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#1072]
In PR #960 we introduced a code to avoid reading the same data twice, if the correlation time is smaller than the chunk size (lag  <= cs).

@cwehmeyer reported a fairly large speed up for his analysis pipeline, if he obeys this condition. In principle we should warn the users, if they violate this condition or, in a more automatic fashion set the default chunk size (which I guess is used most of the time) to fit the lag time (and print a warning that it has been adopted).

**Comment by marscher** [comment]
we could add an estimation parameter chunk_size='auto' to running_covars based estimators to make an optimal choice here. The parameter will be propagated to the primary reader, what do you think?
It has minimal impact on the existing API and will lead to better performance automatically.

**Comment by franknoe** [comment]
Isn't the chunk size already chosen automatically? I think it should be in general as large as possible within a maximum memory consumption. E.g. if we allow to use 100 MB for a chunk, and the dimension is given, that allows a certain chunk size that can be read.

If the lag time is smaller than this chunk size (which should be in *most* cases), then we can re-use the same chunk except when we're getting close to the end of a chunk. If it's larger, we either have to allow a larger memory limit (which might be something the user can do), or accept a slowdown. 

I think reuse vs re-read should only cause a factor two difference in speed. There is a nonlinear factor that has to do with the fact that if we compute dot products between data matrices, large data matrices perform better per row than small matrices, because caching is more efficient. So this is another reason why large chunks are good, but it has nothing to do with I/O.

**Comment by marscher** [comment]
we now have a fixed chunk size of 2 MB, which can be set via the config interface.
