### ISSUE TITLE
Warning: 'OOMReweightedMSM' object has no attribute '_is_estimated'

### ISSUE THREAD

**Issue by thempel** [markovmodel/PyEMMA#1135]
There seems to be a problem with the `_is_estimated` attribute of `OOMReweightedMSM`. The following minimal example reproduces this error. Pyemma version 2.4.

```python
import pyemma
import numpy as np

dtraj = np.random.randint(0, 10, 100)
oom = pyemma.msm.estimate_markov_model(dtraj, 1, weights='oom')
hmm = oom.coarse_grain(2)
hmm.cktest()
```

**Comment by marscher** [comment]
So basically this happens both for ML and OOM, not as reported exclusively for OOM.
The "_is_estimated" attribute, which is a bloody ugly hack to make things work, gets lost along the way of doing the parameter scan of several lag times (cktest). Since the hmm requires an estimated MSM (ML or OOM), which is unchecked, to be passed during the construction of the hmm class, but clone_estimator only copies estimation parameters (ctor args), all the estimated 
stuff gets lost.

The parameter study stuff has been taken from sklearn, which of course assumes sklearn compatible design. Since the MSM related stuff breaks the assumption, that an estimator is fully defined by its parameters (ctor args), we can not directly use this logic here. To avoid the bug, we could simply do a deep copy of the estimator, which could easily blow the memory for large parameter sets, because it copies much more than necessary. Or come up with a sane split of estimator and model, which requires deep and carefully performed refactoring (time consuming), in order to be able to copy only needed stuff.
