### ISSUE TITLE
dtrajs removal

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#1137]
Hi,

sorry, I just noticed that I must have overlooked the merging of #1082, that happened a month ago:
    https://github.com/markovmodel/PyEMMA/commit/16dd0c3527322850e58dc185999233ddc32fb58f
But the changes seem distributed over several merges, so I'm a bit confused what happened when.

This is something I asked to review but didn't and we haven't discussed it and solved the conceptual questions. Unfortunately not all changes that are made a good, and they affect the API, so we need to sort this out asap. Did this already go into a release or can we roll this back at least partially without affecting releases?

Several issues, and unfortunately they are not all trivial to solve:
- hmm method: should be deprecated and removed altogether. This is a new estimator.
- coarse_grain: this is more tricky. Currently this just maps to call hmm, but in the future I'd like it to call different MSM coarse-graining methods that give you something that is 'closer' to the actual MSM. Some of these methods might need just the transition matrix, most are probably covered by the transition matrix and the count matrix. Maybe there are some that need the dtrajs, but we can probably do without. So: what about the count matrix - does it stay part of the MSM estimator?
- cktest: I'm not sure what the plan is after the deprecation period. To get an sklearn-style call we would need something like ```cktest(dtrajs, nsets, ...)```. In any case dtrajs wouldn't be optional after the deprecation period, so I don't think we can do this without a discontinuous API change.

The question remains if there isn't a better way to separate estimators and models that doesn't have these problems. What do we really want to be able to save and recover? dtrajs are an estimator property, the model is instead what we want to save or load. Do we really need to remove the dtrajs from the estimator. 

Sorry for stopping this, but I don't think any of these things should be merged to master/devel before we clarified these questions. So if at all possible I suggest to extract these changes and move them into on different (public) branch, where we raise this baby until we agree on a solution.

**Comment by marscher** [comment]
In Houston we've agreed upon the removal. Of course we can undo everything, because nothing has been released yet. I still don't see, why an estimation input argument is a property of an Estimator. Of course it is convenient to store it. In order to disentangle Models from Estimators, I still encourage to remove it.

The API changes to coarse_grain are carefully deprecated. The dtrajs arg is the moment (merge of #1082) optional (None) and it is being checked for None, which will in case trigger a DeprecationWarning, that this arg will be mandatory in the future. If no dtrajs are passed, the deprecated dtrajs_full property is being passed. So there there is, at the time of writing, no change to the API at all. Of course this would change in the future (eg. at version 2.6, so users will see the warning for at least one release, before we would finally remove dtrajs storage). You're right, this is finally an API breakage.
The count matrix is an derived (estimated) attribute of the estimator, so it remains part of it.

The same thing applies for the cktest method.

I'm fine with removing the hmm method.

I'm not sure I understand your last comment on serialization. Do you say, we should only be able to save Models and not the Estimator (we will forget about the estimation parameters, so how useful would that be? Users would have to store these separately, because it is an important information, isn't it?)
Still we can save the model and the estimation parameters, even if we decide to en capsule dtrajs in the estimator. It is just not clean (in terms of sklearn style).

**Comment by marscher** [comment]
I've reverted those changes.

**Comment by marscher** [comment]
After thinking about this again, I strongly vote against remove dtrajs for the following reasons:
* API breakage
* convenient use of several important features
* serialization just works fine with dtrajs, since we can save the Estimator and the Model individually if desired.

Please re-open, if dtrajs removal is still a concern for future development.
