### ISSUE TITLE
Deprecate Python 2.7

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#1140]
Reasons to do so:
1. It is old
2. We can not use fancy new language features of Python 3.x.
3. Extra maintenance effort to support both major versions.
4. It is officially deprecated by the Python community. End of life https://pythonclock.org/
5. With the aid of conda it is super easy to set up a 3.x environment even on old clusters etc.

I can't image any cons atm, please add them to the discussion, if can come up with some good arguments.

As for a deprecation strategy, we could add a UserWarning if he/she is still using plain old Python 2.7 in the next service release and finally remove the build matrix support for 2.7.

**Comment by jchodera** [comment]
relevant: http://www.python3statement.org/

**Comment by mpharrigan** [comment]
+1

similar discussion here https://github.com/msmbuilder/msmbuilder/issues/852

**Comment by franknoe** [comment]
Ok, let's do this. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by marscher** [comment]
done

**Comment by Lnaden** [comment]
I see no reason to not do this, I would even like to see this extended to the larger Omnia collaboration. There is one problem that I foresee which just requires informing the users. 

Many users will still try to use Python 2 since that is the default Python shipped with many OS's, especially new users. They will see the default version, start with that base version of conda, then try to install the package and probably get an older version. This can mostly be fixed with user education and ample warnings, but it will be a reoccurring issue until Python 3 becomes the default shipped with OS's. Should not be too large a problem though.

**Comment by jchodera** [comment]
What if we pushed hard to have new users install `miniconda` by updating our getting-started docs to include that step?

**Comment by marscher** [comment]
people who are able to compile stuff them self, should also be able to distinguish Python2 and 3. If not we can append the 3 suffix to the invocation of setup.py or pip.
As for the idea of pushing somebody, I think using conda is already the recommended platform for most of Omnias projects. The choice of platform still should remain a users choice for various reasons. Being to restrictive there would potentially hinder people using the software.
