### ISSUE TITLE
TRAM notebook fails to compute pcca with shape mismatch

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#1208]
The notebook PyEMMA.thermo.estimate_multi_temperatur_-_asymmetric_double_well fails during computing PCCA with the following error:

cell 8, input: 
```
# Run PCCA to find metastable sets
msm.pcca(2)
dtram.msm.pcca(2)
tram_obj.msm.pcca(2)
# .... 
```
trace:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/workspace/pyemma/pyemma/msm/models/msm.py in pcca(self, m)
    909             # this will except if we don't have a pcca object
--> 910             if self._pcca.n_metastable != m : # or self._pcca.P is not self.P:
    911                 # incorrect number of states or new transition matrix -> recompute

AttributeError: 'ThermoMSM' object has no attribute '_pcca'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-8-1846f2c269b7> in <module>()
      1 # Run PCCA to find metastable sets
      2 msm.pcca(2)
----> 3 dtram.msm.pcca(2)
      4 tram_obj.msm.pcca(2)
      5 

~/workspace/pyemma/pyemma/msm/models/msm.py in pcca(self, m)
    913         except AttributeError:
    914             # didn't have a pcca object yet - compute
--> 915             self._pcca = PCCA(self, m)
    916 
    917         # set metastable properties

~/workspace/pyemma/pyemma/msm/models/pcca.py in __init__(self, msm, m)
     50 
     51         # coarse-grained stationary distribution
---> 52         self._pi_coarse = np.dot(self._M.T, self._pi)
     53 
     54         # HMM output matrix

ValueError: shapes (2,37) and (48,) not aligned: 37 (dim 1) != 48 (dim 0)
```

Note that I recently merged #945, which did not contain a new test. Could this be related? 

ping @fabian-paul, @cwehmeyer

**Comment by marscher** [comment]
@franknoe should we consider this a blocker for 2.5?

**Comment by fabian-paul** [comment]
#945 is unrelated to this.

**Comment by fabian-paul** [comment]
This looks like the consequence of a design error. In dTRAM, the size of pi doesn't have to match the size of T by construction. They are defined on different set of states.
BTW this is something that I (as an enhanced sampling user) am unhappy with since the earliest days of emma2. I should have complained louder. T and pi should ideally be defined on the same state set and have missing states labeled.

Here are some ideas:

* As a fix we could rewrite PCCA such that pi is re-estimated form T. (This is how T matrix coarse-graining was implemented before somebody changed PCCA and is the reason why the TRAM notebook was even working in the past.)
* Alternatively we could change the meaning of the `pi` property in `ThermoMSM`s. That is we remap the current `pi`  to the new extra property `consensus_pi` (not to be confused with `pi_full_state`!) and implement a new `pi` property that returns a pi that is compatible in size with T. This second option appears more consistent to me (within the confines of the current Pyemma design).
* Other suggestions welcome...

**Comment by franknoe** [comment]
I'm fine with version 1. I don't understand version 2 - what is ``consensus_pi`` ?

**Comment by marscher** [comment]
Note that in pyemma we now assume that P and pi in the MSM object are matching. I think this should also hold for DTRAM. I think the second option sounds interesting.

In the meantime I will revert PCCA to recompute pi.

**Comment by marscher** [comment]
Even when we recompute pi from P every time, we still get the following error during plotting the DTRAM msm object:
``` python
IndexError                                Traceback (most recent call last)
<ipython-input-8-1846f2c269b7> in <module>()
     23     c=msm.metastable_assignments, cmap=mpl.cm.prism, s=80, label='MSM', marker='d')
     24 ax.scatter(
---> 25     centers[dtram.active_set[dtram.msm_active_set], 0], dtram.f[dtram.msm_active_set],
     26     c=dtram.msm.metastable_assignments, cmap=mpl.cm.prism, s=80, label='dTRAM')
     27 ax.scatter(

IndexError: index 39 is out of bounds for axis 0 with size 39
```

**Comment by marscher** [comment]
when I replaced dtram.msm_active_set with dtram.msm.active_set, it works.

**Comment by fabian-paul** [comment]
Hey @cwehmeyer @marscher let's have a final look at this together, just to be sure that it's really solved. 
@franknoe : `consensus_pi` would be the stationary distribution in a given ensemble that is computed from all data (using reweighting). I've heard this word (consensus stationary distribution) in the Roux lab and it makes sense to me. 
`consensus_pi` would be defined for a larger set of states than the transition matrix (but in general not on the full set of states).
