### ISSUE TITLE
HMSMSampled submodel is broken (and untested)

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#1239]
This method is also never in use, because the model itself is most likely always used in conjunction with BayesianHMSM (which overrides submodel). We should either fix this method or delete it. 

It does not work, because it invokes a parent constructor with wrong arguments.

**Comment by franknoe** [comment]
Are you referring to this function? That is definitely needed, but I'm not sure if it is tested. 
https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/msm/estimators/bayesian_hmsm.py#L323
That seems to fine, at least the arguments seem to match the parent function.

Or this one?
https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/msm/models/hmsm_sampled.py#L57
what is the problem here?

I don't want to delete it, why not just fix it if there's an invalid call.

**Comment by marscher** [comment]
The title of this issue should have made it clear, which class I'm talking about - sorry. The bogus invocation is in SampledHMSM. There are no parameters like 'ref' and 'conf' in the parent class.

**Comment by marscher** [comment]
for samples and conf, we can solve it directly, while for ref(erence?), we should add a property.
