### ISSUE TITLE
timescales_hmsm with n_jobs > 1 not working

### ISSUE THREAD

**Issue by thempel** [markovmodel/PyEMMA#1266]
With the latest PyEMMA release 2.5.1, it seems that using multiprocessing with implied timescales estimation for HMMs is somewhat broken. The following minimal example reliably crashes:

```python
import pyemma
import numpy as np
dtrajs =[np.random.randint(0, 10, 1000) for _ in range(10)]
pyemma.msm.timescales_hmsm(dtrajs, 2, lags=[1, 2, 3], n_jobs=2)
```

It raises `RuntimeError: Estimation has failed at ALL lagtimes.` Works with `n_jobs=1` or release 2.4. Can anyone reproduce this?

**Comment by marscher** [comment]
On 02.03.2018 15:44, thempel wrote:
> With the latest PyEMMA release 2.5.1, it seems that using multiprocessing with implied timescales estimation for HMMs is somewhat broken. The following minimal example reliably crashes:
> 
> ```python
> import pyemma
> import numpy as np
> dtrajs =[np.random.randint(0, 10, 1000) for _ in range(10)]
> pyemma.msm.timescales_hmsm(dtrajs, 2, lags=[1, 2, 3], n_jobs=2)
> ```
> 
> It raises `RuntimeError: Estimation has failed at ALL lagtimes.` Works with `n_jobs=1` or release 2.4. Can anyone reproduce this?
> 
Thanks. I'm getting the following details:

RuntimeError: Estimation has failed at ALL lagtimes. Details:
['Error at lag time 1: float division by zero',
  'Error at lag time 2: float division by zero',
  'Error at lag time 3: float division by zero']

This is caused by passing self.nstates == 0 to bhmm, which divides by 
zero then.

So we need to find the cause for nstates=0 in the first place and add 
tests with multiple jobs. I though we already had those...

**Comment by marscher** [comment]
On 02.03.2018 15:44, thempel wrote:
> With the latest PyEMMA release 2.5.1, it seems that using multiprocessing with implied timescales estimation for HMMs is somewhat broken. The following minimal example reliably crashes:
> 
> ```python
> import pyemma
> import numpy as np
> dtrajs =[np.random.randint(0, 10, 1000) for _ in range(10)]
> pyemma.msm.timescales_hmsm(dtrajs, 2, lags=[1, 2, 3], n_jobs=2)
> ```
> 
> It raises `RuntimeError: Estimation has failed at ALL lagtimes.` Works with `n_jobs=1` or release 2.4. Can anyone reproduce this?
> 

I think I got it. This is caused by some serialization issue. The 
ML-HMSM makes nstates an input parameter, while the model class (MSM) 
handles this as a derived attribute (from the transition matrix).

I think the easy way to fix this would be to avoid overwriting nstates 
in the HMSM, but in the long term we should fix this in a way avoiding 
overlaps in derived and input parameters.
