### ISSUE TITLE
errors on trajectory_weights()

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#1276]
This may have a trivial answer, but is there a quick and easy way to estimate errors on the assigned trajectory weights, so that in addition to computing the expectation value of an observable I can also compute the error associated to that expectation value?

**Comment by franknoe** [comment]
I don't see how to compute uncertainties on the trajectory weights themselves, because these are weights per data point, i.e. they are not an expectation. But the stationary distribution underlying these weights have uncertainties, and so do expectation values of observables computed from them. In BayesianMSM and BayesianHMSM you have methods to compute uncertainties on the stationary distribution, for example.
An of course there's always the option to do trajectory bootstrapping.
