### ISSUE TITLE
Add option to give a linear operator to the transformation pipeline

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#128]
This is a request in the context of hTICA, but might be otherwise also useful, perhaps.  

If I **already** have a transformation matrix and list of distances I want to operate on (s.t I rotate them into hTICs), this would be a useful feature, IMHO.

**Comment by franknoe** [comment]
I believe was (partially) discussed today. We could have ways to instantiate existing transformers by not feeding them data but their parameters. Such a transformer only does a map and non of the parametrize stuff. Similar to the feature reader. So this is a matter of providing corresponding API functions, not new Transformers.

hTICA on the other hand would be a transformer on its own because it streams the data differently from ordinary TICA. It could share the mapping method with TICA because the hierarchical mapping could be flattened, but that alone is probably not worth doing a subclass.
