### ISSUE TITLE
PCCA coarse_grained_transition_matrix

### ISSUE THREAD

**Issue by lucl13** [markovmodel/PyEMMA#1298]
Hello,

I got a PCCA coarse_grained_transition_matrix which contains several negative values? (What does it mean?) Isn't is obtained from the MSM transition matrix?  My MSM is satisfied according to Implied timescales plot and CK test. 

Thanks,
Chenlin

**Comment by thempel** [comment]
Hi Chenlin,

This is a property of PCCA+ as it is implemented right now. The process that is described by the coarse transition matrix need not be a Markov process; you can think of the coarse transition matrix as the propagator of this coarse process. You will find that the rows are normalized to one. So a working validation of the MSM does not necessarily yield a positive PCCA+ transition matrix, unfortunately. For more details, have a look e.g. at this paper:

S. Roeblitz and M. Weber, Fuzzy spectral clustering by PCCA+: application to Markov state models and data classification. Adv Data Anal Classif 7, 147-179 (2013).

Cheers,
Tim

**Comment by lucl13** [comment]
Hi Tim,

Thank you. If the coarse transition matrix is not a transition matrix, what should I do to conduct a  transition path theory analysis on my MSM based on the coarse process?

Thanks,
Chenlin

**Comment by franknoe** [comment]
For some reason my response didn't show up here:

If there is a timescale separation at the number of states picked, these negative entries should be small. So if they are small, just ignore them and interpret them as zeros. The transition matrix will still yield a valid probability distribution if you feed a valid probability distribution in (i.e. if you do    p_t    = P p_0 and p_0 is a valid probability distribution, p_t will not have negative entries).

If you have large negative entries this is a sign that your system is not metastable for the number of coarse states picked. Have a look at your timescales/eigenvalues. If you have a gap after the second eigenvalue or first finite timescale, you can pick 2 states, etc. If there is no gap / if you always get significant negative entries in the coarse-grained transition matrix, then there is no good choice.

In general, if you just want a valid coarse-grained (few-state) transition matrix in the end, I recommend trying HMMs instead of MSMs (timescales_hmsm, estimate_hmsm, etc).
