### ISSUE TITLE
Average configurations of PCCA samples

### ISSUE THREAD

**Issue by lucl13** [markovmodel/PyEMMA#1307]
Hello,

Is it correct if I just get an average configuration for PCCA samples of each metastable states and use these average configurations to do further analysis? I am working on a project related to protein configuration transmission and binding kinetics. My concern is if average process will destroy the original info got from PCCA clustering or not. For example,  average configuration of PCCA 1 samples turns out to be the same with PCCA 2.

Thanks,
Chenlin

**Comment by gph82** [comment]
Hi, 

averaging configurations is in principle not a very good idea unless you are really sure what you are doing. It will destroy information which, a priori, you might be interested in (as you say). Think of a sidechain angle which is bi-modal in the state and you average over it. If you know that you don't care about that angle, then you're good, but this might not always be the case. And that is assuming that you can orient the samples properly in space.

I 'd much rather produce an sample weighted by the PCCA-distribution and look at it as an overlay or use the argmax of that distribution. 

Does that help?

**Comment by fabian-paul** [comment]
Hi Chenlin, 
when computing averages of the metastable distribution, there is an important detail to be aware of.
For the case of the MSM (not the HMM), the metastable distributions are computed by multiplying together the metastable memberships and the stationary vector element-wise. 
`meta_dist[:, :] = pi[:, None]*memberships[:, :]` 
Now if there are large differences in the stationary vector, this can lead to strange effects.

Take for example the case of a model with 2 microstates and two macrostates, where one of the stationary weights is very close to one and the other is very close to zero.
pi[0] = eps \approx 0
pi[1] = 1-eps \approx 1

Now:
meta_dist[0, 0] = pi[0]*memberships[0, 0]
meta_dist[1, 0] = pi[1]*memberships[1, 0]
meta_dist[0, 1] = pi[0]*memberships[0, 1]
meta_dist[1, 1] = pi[1]*memberships[1, 1]

or

meta_dist[0, 0] = eps*memberships[0, 0]
meta_dist[1, 0] = (1-eps)*memberships[1, 0]
meta_dist[0, 1] = eps\*memberships[0, 1]
meta_dist[1, 1] = (1-eps)*memberships[1, 1]

Finally, we want to compute the averages of some observable x over the metastable distributions:
mean(x|metastale_state=0) = x[0]\*meta_dist[0, 0] + x[1]\*meta_dist[1, 0] 
 = x[0]\*eps\*memberships[0, 0] + x[1]\*(1-eps)\*memberships[1, 0]
 \approx x[1]\*memberships[1, 0]


mean(x|metastale_state=1) = x[0]\*meta_dist[0, 1] + x[1]\*meta_dist[1, 1] 
 = x[0]\*eps\*memberships[0, 1] + x[1]\*(1-eps)\*memberships[1, 1]
 \approx x[1]\*memberships[1, 1]

As you can see, because of the large differences in pi, x[0] is never used in the computation of the averages.
A possible solution in such a situation is not to work with the fuzzy metastable distributions, but to start from the crisp metastable sets and to work you way onwards from the metastable sets.

Best,
Fabian
