### ISSUE TITLE
time step unit in TICA, timescales_msm

### ISSUE THREAD

**Issue by and-tos** [markovmodel/PyEMMA#1368]
Hi all,
it's not clear to me whether the time step unit is the time between to frames of my trajectory or the time step in my simulation. So when I run my simulation with a 2fs time step and write a frame every 2ps, and I set lag=1000, is my lag time 2ps or 2 ns?

**Comment by marscher** [comment]
First of all, saving your simulation every 2ps is overkill, because you do will store a lot of noise (bond vibrations are not that interesting right).

The TICA lag time is only used to define the auto correlation, which is maximized by the method. So in your example dt will be equal to 2 ps. If you use a thousand steps for tica (2ns), you will basically kick out processes slower than this lag time, when projecting onto the TICA eigenspace.

When you analyse a MSM on your simulation, you want to scale the kinetic quantities with the saving interval of that simulation(s), to get a physical meaningful result. You can set this by specifying the dt_traj parameter. This will be used automatically in subsequent calculations.

**Comment by and-tos** [comment]
Thanks for the advice!
