### ISSUE TITLE
 HMSM: number of hidden states

### ISSUE THREAD

**Issue by and-tos** [markovmodel/PyEMMA#1374]
Hi all,
it's not clear to me how to set the number of hidden states when calculating a hidden MSM. Should this number be equal to the number of microstates from prior clustering?
I am refering to pyemma.msm.timescales_hmsm
Thanks a lot for your help!

**Comment by thempel** [comment]
Hi @andt88,
No, the number of hidden states is mostly chosen smaller than the number of microstates. It can be seen as an equivalent to the number of macrostates you choose for the PCCA coarse graining. 
In general, this choice depends on the system and the model you want to obtain. We explain this in more detail and with examples in our new [tutorial notebooks](https://github.com/markovmodel/pyemma_tutorials).
Cheers,
Tim

**Comment by and-tos** [comment]
Thanks a lot! Unfortunately I cannot load them. I get this error: Sorry, something went wrong. Reload?
So does it make sense to build a MSM prior to an HMSM to estimate the number of meta-stable states and use this as input for the HMSM?

**Comment by and-tos** [comment]
So I tried generating an ITS plot with a HMM, but it looks very different from the on I generated with a regular MSM.
Does anybody know why there is such a difference between the two models?

HMM

```
nstates = 7
lags=10000
its = msm.timescales_hmsm(dtrajs, nstates, lags=lags, errors='bayes', n_jobs=4)
mplt.plot_implied_timescales(its, show_mean=False, units='ns', dt=0.005, linewidth=2)

```

![its_hmm](https://user-images.githubusercontent.com/36545428/47964495-39126800-e03b-11e8-9673-923c242643fc.png)


MSM
![its_msm](https://user-images.githubusercontent.com/36545428/47964463-cf925980-e03a-11e8-85e5-be6c763216be.png)

**Comment by thempel** [comment]
1) Yes, it makes sense to build an MSM before the HMM to estimate the number of hidden states. Look for the spectral gap. In your case it looks like a gap between the 4th and 5th ITS, maybe try 5 hidden states then. You still have to fine-tune this number because the MSM might not find all of the processes that the HMM finds. Also, you might want to see if the HMMs models what you  are interested in.
2) The HMM implied timescales seem to find some disconnectivities in your data. Since your MSM looks rather converged, I would try to fine-tune the number of hidden states and to stay with smaller lag times. If you turn-up the lag time too much, you might loose the processes that your HMM finds for smaller lag times due to finite sampling. 
As the HMM estimates the transition matrix between hidden states and not directly between the clustered microstates, the plots don't need to look the same. 
3) We will try to fix the error you mentioned above. Can you please specify when it occurred? @marscher

**Comment by and-tos** [comment]
Thanks a lot! The error in the python notebook occured last thursday but it was running fine yesterday.
Are disconnectivities caused by insufficient sampling?

**Comment by thempel** [comment]
Insufficient sampling is the most likely explanation, yes.

**Comment by thempel** [comment]
Ok, the error you got with the pyemma tutorials seems to be a temporary issue with github displaying Jupyter notebooks. It worked for me now. 
I strongly recommend to take another look at the tutorials. Many of the questions being asked here are explained there in more detail and with showcase examples. You can download the tutorial as a conda package (explained in the readme) or use it online with binder (link "launch binder" next to the green "passed" flag).
