### ISSUE TITLE
Separating bound from unbound Microstates

### ISSUE THREAD

**Issue by and-tos** [markovmodel/PyEMMA#1425]
Hi,

I am using PyEMMA 2.5.6 to analyze protein protein-ligand interactions. 
In this paper https://www.nature.com/articles/ncomms8653/#supplementary-information, the authors mention that they projected the featured trajectory using TICA and then separated unbound microstates. Since after TICA projection the contact map is reduced I was wondering how I can identify microstates that are unbound. 
Thanks a lot for any help!

**Comment by thempel** [comment]
You could manually define a coordinate that describes ligand binding. Since this is highly system dependent, I can't help you with that, but it could be one of your contacts, a set of contacts or a minimum distance between several atoms with a cutoff. Once you have this, you can essentially split your clustered micro states into bound and unbound.
