### ISSUE TITLE
some quick questions in dtram estimation 

### ISSUE THREAD

**Issue by yunhuige** [markovmodel/PyEMMA#1429]
Hi PyEMMA,

I'm using dtram/tram estimator on a dataset with both unbiased simulation and umbrella simulations. Here are some questions I have:

First, this is how I initialize dtram estimation:
`dtram_obj = dtram(ttrajs, dtrajs, bias, lagtime, unbiased_state=int(0))` and `int(0)` is the unbiased thermodynamic ensemble. 

1/ Is the state index of estimated population `dtram_obj.stationary_distribution` corresponds to the state index in `dtram_obj.active_set`? For example, is the 1st state population corresponds to the 1st state in `active_set`?

2/ I compared state population from dtram estimation (`dtram_obj.stationary_distribution`) and the state population from the unbiased ensemble (`dtram_obj.msm.pi`) and I found they are not identical. Actually, in my calculation, they are very different. Should I expect this difference? Or it's a bad sign showing I did something wrong. If they should be different, what is the relationship between these two sets state population?

3/ It seems all of the attributes in `MEMM` object (which is the returned object from dtram) are about thermodynamic properties (e.g stationary population, free energy, etc) but no kinetics information (implied timescale for example). I can use the unbiased ensemble (`dtram_obj.msm`) to get those kinetics information as well as the transition matrix. But I'm not suer if I should use them. My understanding is dtram is the estimation which is done by reweighing the original transition matrix with biased simulations. Then with the new transition matrix, we can compute thermodynamic and kinetic properties. But given the fact (1) `dtram_obj.stationary_distribution` is different from `dtram_obj.msm.pi` (as I mentioned in my 2nd question) and (2) no kinetics information available in returned object from dtram, I'm a little confused. Does `dtram_obj.msm` have reweighed transition matrix and those quantities (thermodynamic and kinetics) are computed based on that matrix? Or that matrix is just based on unbiased simulation and should be the same if no umbrella simulation data is used? 

4/ This is also related to my previous question, how can I save the 'final' transition matrix (reweighed with all biased sampling)? Is `dtram_obj.msm.transition_matrix` the one I should look at?

5/ This is a minor question, I'm clear about `ttraj`, `dtraj` and `btraj` in tram estimation. But for dtram, how should I compute bias to feed dtram estimator? Right now, I'm using `computePMF` function in PyMbar to compute PMF of each bin in each thermodynamic ensemble. The bin here is the state index in MSM. Is this the correct way to compute bias for dtram? It is not super clear in the online documentation and I didn't find too much information in tutorial (jupyter notebooks) either.  

Since these questions are not related to specific scripts so I didn't attach my `conda list` here. If you need those information, I can attach them later. I'm using PyEMMA 2.5.4 (py27hf8a1672_1). 

Thank you for your time and I appreciate your help. 

Best,
Yunhui

**Comment by fabian-paul** [comment]
Hi Yunhui,

> 1/ Is the state index of estimated population `dtram_obj.stationary_distribution` corresponds to the state index in `dtram_obj.active_set`? For example, is the 1st state population corresponds to the 1st state in `active_set`?

That's correct.
 
> 2/ I compared state population from dtram estimation (`dtram_obj.stationary_distribution`) and the state population from the unbiased ensemble (`dtram_obj.msm.pi`) and I found they are not identical. Actually, in my calculation, they are very different. Should I expect this difference? Or it's a bad sign showing I did something wrong. If they should be different, what is the relationship between these two sets state population?

They should be the same except for indexing (and except for number of states).

for i, j such that dtram_obj.msm.active_set[i] == dtram_obj.active_set[j]
	dtram_obj.msm.pi[i] == dtram_obj.stationary_distribution[j]

This can get quite confusing pretty quickly (IMHO that's a design flaw in PyEmma) . I find it more useful to use the *_full_state properties.

> 3/ It seems all of the attributes in `MEMM` object (which is the returned object from dtram) are about thermodynamic properties (e.g stationary population, free energy, etc) but no kinetics information (implied timescale for example).

That's correct.

> I can use the unbiased ensemble (`dtram_obj.msm`) to get those kinetics information as well as the transition matrix. 

Exactly.

> But I'm not suer if I should use them. My understanding is dtram is the estimation which is done by reweighing the original transition matrix with biased simulations. 

No, that's actually not the case. Or only in an indirect way. You can have a look at slide # 24 in [TRAM-short-presentation.pdf](https://gist.github.com/fabian-paul/c175020fe466902eaa3c22a7cb034ef5). TRAM makes every transition matrix consistent with its stationary distribution and links stationary distributions across ensembles (themodynamic states). Unlike in DHAM (Rosta & Hummer) transition probabilites are not reweighted across ensemble. Please have a look at the slide for more information.

> Then with the new transition matrix, we can compute thermodynamic and kinetic properties. 

This is half true, half false. You could compute the thermodyamic properties from the transition matrix, but only in special cases. Only a transition matrix where every state is visited would give the full thermodynamic information. Often this is the unbiased thermodynamic state. But sometimes not all relevant states are visited by the unbiased simulation. It is better to use the consensus stationary distribution (dtram_obj.stationary_distribution) to estimate thermodynamic properties. Since stationary information is reweighted across ensembles, the consensus distribution contains information from all the ensembles. But since the individual transtion matrices are typically defined on smaller sets of states, their stationary distribution will contain only part of this global information.
For kinetic properties one is limited to the transtion matrix of the unbiased ensemble.

> But given the fact (1) `dtram_obj.stationary_distribution` is different from `dtram_obj.msm.pi` (as I mentioned in my 2nd question) and (2) no kinetics information available in returned object from dtram, I'm a little confused. Does `dtram_obj.msm` have reweighed transition matrix and those quantities (thermodynamic and kinetics) are computed based on that matrix? Or that matrix is just based on unbiased simulation and should be the same if no umbrella simulation data is used?

Please have a look at the slides. dtram_obj.msm.pi is essentially the same as the consensus distrubution (dtram_obj.stationary_distribution). It's just limited to a smaller subset of states (to those that have kinetic informationin the unbiased ensemble). There is no "consensus transition matrix" because there are no reweighted transition matrices in TRAM.
 
> 4/ This is also related to my previous question, how can I save the 'final' transition matrix (reweighed with all biased sampling)? Is `dtram_obj.msm.transition_matrix` the one I should look at?

Such a thing does not exist in the TRAM algorithms (unlike in DHAM). TRAM was developed such that it uses only exact theorems from statistical mechanics and Markov modeling (or more exactly: mathematical relations that can become exact in the limits of small microstates, large lag times and the limit of infinitely many short trajectories.) Reweighting transitions is by construction inexact (or rather: the conditions under which they become exact are not well understood.) That's why this was not used in formulation the TRAM family of algorithms. 
Our assumption was that in practice the state space that is sampled in the unbiased ensemble is large enough such that one can simply take dtram_obj.msm as the final MSM. I think that this is justified, since growing the unbiased ensemble is kind of easy: just start trajectories from all Markov states and run them without bias. 
 
> 5/ This is a minor question, I'm clear about `ttraj`, `dtraj` and `btraj` in tram estimation. But for dtram, how should I compute bias to feed dtram estimator? Right now, I'm using `computePMF` function in PyMbar to compute PMF of each bin in each thermodynamic ensemble. The bin here is the state index in MSM. Is this the correct way to compute bias for dtram? It is not super clear in the online documentation and I didn't find too much information in tutorial (jupyter notebooks) either.

The correct answer is not to use dTRAM in this case but to use TRAM. There is no information on this, because it is simply a modeling assumption that went into the formulation of dTRAM (you could say a pretty unrealistic one). To be clear, the assumption is that the bias energy is constant in every bin. So if the bias is a simple function, like a wide quadratic umbrella potential that depends on a single order parameter, it is possible to optimize the clustering to make the basic assumption of dTRAM fulfilled. One would have to tweak the clustering a bit: first do a 1-D clustering along the order parameter with a reasonable (maybe fixed) grid size. Then cluster the orthogonal space within every grid cell. Of course this needs some re-indexing such that one ends up with cluster labels that are unique integers.
If you want to rather do something more simple and more approximate, you could average the Boltzmann factors (e^-beta U_bias) within every microstate and take minus the logarithm divided by beta to convert it formally into a bias energy.
Using MBAR does not sound like a good idea. First of all, you are interested in the bias energy of the microstate and not in the free energy of the microstate. MBAR gives you the latter. The free energy includes the contribution from the underlying MD force field and is distinct from the bias energy even though it might look similar sometimes (like when using stiff umbrella potentials).

Hope that helps,
Fabian

**Comment by vvoelz** [comment]
Hi Fabian:

Thank you so much for the detailed responses to Yunhui's questions.  We're obviously *still* trying wrapping our minds around your advanced algorithm :) 

One thing I would take issue with is your comment:

> If you want to rather do something more simple and more approximate, you could average the Boltzmann factors (e^-beta U_bias) within every microstate and take minus the logarithm divided by beta to convert it formally into a bias energy. .... you are interested in the bias energy of the microstate and not in the free energy of the microstate. 

Shouldn't the bias energy be just the same thing as a free energy estimation? (which is why we are trying to use MBAR for this purpose, i.e. to rigorously compute the best possible estimation of the bias for each state across the thermodynamic ensembles).  Put another way, if we found the free energy difference for state _i_ between ensembles _k_ and _l_ to be ∆ _f_, the dTRAM result would be the same as if we applied a constant bias of ∆ _f_ to state _i_ for ensemble _l_ , where _k_ is the reference.

Could you comment on this?
Vince

**Comment by fabian-paul** [comment]
Ah, I see now.  So you are saying that the bias energy of a microstate actually is the free energy difference of that microstate between the biased and the unbiased ensembles. I agree with this interpretation. However I don't have any proof for this. Do you know how this could be shown formally?
When using MBAR, you surely mean that you run MBAR separately on the data from each microstate. Is that what you do?

**Comment by vvoelz** [comment]
Hi Fabian -- I believe the formal demonstration is just the [Zwanzig relation](http://www.alchemistry.org/wiki/Exponential_Averaging); i.e. *by definition* the free energy is the average of the (e^-beta U_bias) factors.  Doing this exponential averaging over a set of finite samples is an estimator often called "EXP"; it suffers from bias since samples with low U_bias values will receive very large weights (e^-beta U_bias). It is well-known that MBAR suffers less from this kind of bias, so one should use MBAR for purpose, right?    Or maybe I'm still missing something.

> When using MBAR, you surely mean that you run MBAR separately on the data from each microstate. Is that what you do?

I'm not sure what you mean by "separately"; I mean that I would run an MBAR calculation to get the free energies of each state in each ensemble.  I would use then use these free energies as the discrete-state biases as the input of dTRAM.
