### ISSUE TITLE
Statistically correct calculation of means, correlations and time-lagged correlations in TICA

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#143]
Initial points:

   * Perhaps it is correct to compute mean and instantaneous correlation matrix on t-tau data points only, in order to have a consistent normalization. In any case we are not computing the real mean (which would requiring reweighting out-of equilibrium data), so perhaps all is needed for the empirical mean is that it is consistently computed with the time-lagged quantities, such that all normalizations are OK and we can expect to get eigenvalues below 1.
   * Fabian's suggestion: It should hold that $c_ii(tau) \le c_ii(0)$. This is not guaranteed in the current implementation.

I believe Fabian is right. The consequence is that for a time-lagged (TICA) problem with lag time $\tau$, the quantities should **not** be computed on the largest possible set of data, but rather consistently:

![screen shot 2015-03-25 at 08 12 02](https://cloud.githubusercontent.com/assets/6495810/6819754/a8cce78c-d2c6-11e4-9c3e-a9fa71d01035.png)

Or, if we **define** $N(\tau) = T-\tau$ where $T$ is the total number of trajectory frames, and $N$ is the number of frames in our X chunks (X in the code), then simply:

![screen shot 2015-03-25 at 08 12 43](https://cloud.githubusercontent.com/assets/6495810/6819764/beda1932-d2c6-11e4-8335-bb808fe3ae9e.png)

I think this is the right solution. Another argument is that in MSMs (special case of the variation principle with characteristic basis functions) we do exactly this:

![screen shot 2015-03-25 at 08 15 14](https://cloud.githubusercontent.com/assets/6495810/6819794/1d7c4ea6-d2c7-11e4-9105-4362c1501044.png)

Note the $-1$ is missing because we do not remove an empirical mean.

This solution does not only seem to be correct, but will also lead to the most simple code. We will not have to do any dirty tricks, but we can rather compute $N(\tau)$ by counting the number of frames in our X-variable, directly implement the second set of equations above and do *not* need to care about the trajectory ends for $\mu_i$ and $c_ij(0)$.

Do you agree or disagree?

**Comment by gph82** [comment]
Hi, this indeed seems to make more sense.

I have one question, though. Even if only slightly, doesn't this lead to a $\tau$-dependent mean and a $\tau$-dependent instantaneous correlation matrix? 

I know that for "well behaved", "converged" data, a leaving out $\tau$ frames to estimate the inst. correlation and the mean should not matter. It shouldn't even matter much if it's the first $\tau$ frames, or the last $\tau$ frames, or some $\tau$ random frames in between, because mean and correlation should be stationary for this type of data. 

What about for data that is *not* that well behaved? Are there any foreseeable consequences (at all). Perhaps there aren't any, I do not know.

**Comment by fabian-paul** [comment]
I agree partially. The comparison with the Markov model is a very good point. But you used the irreversible MSM equation. TICA is more of a reverisble method where we use the sledge-hammer method of symmetrizing the time-lagged covariance matrix.
What comes closest to TICA in the world of Markov models is the symmetrized count matrix (we never do this in practice, but we could)
![image](https://cloud.githubusercontent.com/assets/8878525/6824539/6b1eaff6-d2f3-11e4-854e-cec56d60e4ca.png)
(I have used χ for indication functions. I will use x later for general coordinates.)
If I calculate  c ij(0) by the same equations as Frank
![image](https://cloud.githubusercontent.com/assets/8878525/6824547/81782e94-d2f3-11e4-9c9a-c6b0e350f111.png)
Now  c ij(0) = ∑_j c ij holds only if we define c ij(0) to be
![image](https://cloud.githubusercontent.com/assets/8878525/6824552/8a53872a-d2f3-11e4-9019-e1db89182c39.png)
Thus we double count the samples between τ and N - τ.
We may take this as a our general recipe for computing instantaneous correlation functions.
So we define
![image](https://cloud.githubusercontent.com/assets/8878525/6824556/91396906-d2f3-11e4-9752-559bfb8b9e17.png)
The instantaneous autocovariance would be
![image](https://cloud.githubusercontent.com/assets/8878525/6824563/97f99e1e-d2f3-11e4-9bf8-361f53860856.png)
Because for any two numbers a^2 + b^2 ≥ 2ab, we have
![image](https://cloud.githubusercontent.com/assets/8878525/6824574/a20692e0-d2f3-11e4-9a36-87d61d9332bb.png)
and therefore
![image](https://cloud.githubusercontent.com/assets/8878525/6824577/a798a342-d2f3-11e4-9fc0-c6e378c38f7d.png)
or
![image](https://cloud.githubusercontent.com/assets/8878525/6824580/ad2cac2c-d2f3-11e4-95bc-628fe5cca9cc.png)
What do you think?

**Comment by franknoe** [comment]
Am 25/03/15 um 11:58 schrieb gph82:
>
> Hi, this indeed seems to make more sense.
>
> I have one question, though. Even if only slightly, doesn't this lead 
> to a $\tau$-dependent mean and a $\tau$-dependent instantaneous 
> correlation matrix?
>
Yes, absolutely. But everything is tau-dependent for finite data. The 
question is what do we have to do for one TICA problem and within that 
tau is fixed.
>
> I know that for "well behaved", "converged" data, a leaving out $\tau$ 
> frames to estimate the inst. correlation and the mean should not 
> matter. It shouldn't even matter much if it's the first $\tau$ frames, 
> or the last $\tau$ frames, or some $\tau$ random frames in between, 
> because mean and correlation should be stationary for this type of data.
>
> What about for data that is /not/ that well behaved? Are there any 
> foreseeable consequences (at all). Perhaps there aren't any, I do not 
> know.
>
I guess the main point is to have timescales that make sense, i.e. the 
eigenvalues should be below 1. If you just use TICA as a dimension 
reduction method, that does not matter. But if you want to look at the 
TICA timescales directly - and I'm planning to make it easy to do that - 
then you would have a problem if there are eigenvalues greater than 1.


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Fabian: I am not sure if you are suggesting to make a change, because your equations are the usual correlation matrix with symmetrization:

![screen shot 2015-03-25 at 17 25 34](https://cloud.githubusercontent.com/assets/6495810/6829481/0f09a312-d314-11e4-9201-b00ecbd3f648.png)

You argue correctly that $c_ii(0) \ge c_ii(\tau)$, but the crucial change for this property is that we use the same $N(tau)$ for both $c_ii(0)$ and $c_ii(\tau)$.

**Comment by fabian-paul** [comment]
Hi Frank,
the equation for c_ij(tau) in the last comment doesn't look correct. This isn't a correlation because there is no term with x(t)*x(t+tau).
The change that I suggest, is to count the frames between tau and N-tau twice when computing C_ij(0). Then we will have used 2*(N(tau)-tau) frames in the computation of C_ij(0). This is the same number of frames that are used for C_ij(tau). Of course then both C_ij(0) and C_ij(tau) are normalized by 2*(N(tau)-tau). Furthermore C_ii(0)>=C_ii(tau) as I have shown above. And we even use all frames in all computations (albeit with different weights).

**Comment by franknoe** [comment]
I'm sorry, now I see your point. I remove that comment to avoid confusion.

Am 25/03/15 um 17:39 schrieb fabian-paul:
>
> Hi Frank,
> the equation for c_ij(tau) in the last comment doesn't look correct. 
> This isn't a correlation because there is no term with x(t)/x(t+tau).
> The change that I suggest, is to count the frames between tau and 
> N-tau twice when computing C_ij(0). Then we will have used 
> 2/(N(tau)-tau) frames in the computation of C_ij(0). This is the same 
> number of frames that are used for C_ij(tau). Of course then both 
> C_ij(0) and C_ij(tau) are normalized by 2*(N(tau)-tau). Furthermore 
> C_ii(0)>=C_ii(tau) as I have shown above. And we even use all frames 
> in all computations (albeit with different weights).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/143#issuecomment-86110082>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Fab: Do you also suggest to do that for the mean, i.e.

$$
\mu_i = \frac{1}{2 N(\tau)} sum_t^{N(\tau)} = x_i(t) + x_i(t+\tau)
$$

**Comment by fabian-paul** [comment]
Maybe?
At least with that choice, the identity
cov(x,y) = \<(x-\<x\>)(y-\<y\>)\> = \<xy\>-\<x\>\<y\>
will stay true...

**Comment by franknoe** [comment]
I agree. Let me write this down, I think we are converging here.

**Comment by fabian-paul** [comment]
I was puzzled with the connection between the TICA eigenvalues and the inequality C^x_ii(0)>=C^x_ii(tau).
I think I got it now.

Let x be our original coordinates, using the formula above, we have
C^x_ii(0)>=C^x_ii(tau)

After doing TICA, we have new coordinates z. Now if we always use the same way of computing C_ij(0) and C_ij(tau), we will also have C^z_ii(0)>=C^z_ii(tau) no matter how z was computed.
But the z from TICA have additional properties: they are normalized such that C^z_ii(0)=1 and lambda_i = C^z_ii(tau). 
From these tree equations follows that 1 >= lambda_i.

**Comment by fabian-paul** [comment]
I wonder whether using the new way to compute C_ij(0) may improve TICA. (Or worsen TICA?)
With the old way of computing C_ij(0), one could possibly have C^x_ii(0) < C^x_ii(tau) by accident because of finite data. Would TICA then give a large weight to x_i because it would consider it to be a very slow degree of freedom?
I know that this case is constructed artificially and that in practice the effect of finite data should be small. Moreover one would typically increase the lag time, if the acfs of slowest degrees of freedom have not significantly decayed from 1.
But I suspect that with the new way of computing C_ij(0) the acfs will be typically smaller. In some edge cases, when two values C^z_ii(tau) and C^z_jj(tau) are very close, the order of the processes might change with respect to the old way of computing C_ij(0).
Just some random thoughts...

**Comment by franknoe** [comment]
I think that's right. I am writing up our current thoughts in a 
manuscript on implementation details for variational problems that I 
have started

Am 26/03/15 um 11:44 schrieb fabian-paul:
>
> I was puzzled with the connection between the TICA eigenvalues and the 
> inequality C^x_ii(0)>=C^x_ii(tau).
> I think I got it now.
>
> Let x be our original coordinates, using the formula above, we have
> C^x_ii(0)>=C^x_ii(tau)
>
> After doing TICA, we have new coordinates z. Now if we always use the 
> same way of computing C_ij(0) and C_ij(tau), we will also have 
> C^z_ii(0)>=C^z_ii(tau) no matter how z was computed.
> But the z from TICA have additional properties: they are normalized 
> such that C^z_ii(0)=1 and lambda_i = C^z_ii(tau).
> From these tree equations follows that 1 >= lambda_i.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/143#issuecomment-86447876>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
I have written up the results from this discussion in

https://svn.imp.fu-berlin.de/cmb/papers/NueskeWuNoe_VariationalNotes/

**Comment by fabian-paul** [comment]
Just to wrap up. There is one argument for calculating the mean as mu_i = 1/(2N(tau)) sum_t^{N(tau)} [ x_i(t) + x_i(t+tau) ]. Feliks pointed out that in the variational principle the eigenvalue=1 goes away completely and doesn't influence the second eigenvalue if cov(x_i,1)=0 for all i. The practical way to achieve this is to define new coordinates y_i = x_i - cov(x_i,1). This is what we colloquially call "subtracting the mean". The message that we lean from this is that the "mean" we subtract should be defined as cov(x_i,1). Therefore the definition of cov() also defines the way how we have to calculate the mean.

**Comment by franknoe** [comment]
Can you please update

https://svn.imp.fu-berlin.de/cmb/papers/NueskeWuNoe_VariationalNotes/

Thanks!

Am 07/05/15 um 17:52 schrieb fabian-paul:

> Just to wrap up. There is one argument for calculating the mean as 
> mu_i = 1/(2N(tau)) sum_t^{N(tau)} [ x_i(t) + x_i(t+tau) ]. Felix 
> pointed out that in the variational principle the eigenvalue=1 goes 
> away completely and doesn't influence the second eigenvalue if 
> cov(x_i,1)=0 for all i. The practical way to achieve this is to define 
> new coordinates y_i = x_i - cov(x_i,1). This is what we colloquially 
> call "substracting the mean". The message that we lean from this is 
> that the "mean" we subtract should be defined as cov(x_i,1). Therefore 
> the definition of cov() also defines the way how we have to calculate 
> the mean.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/143#issuecomment-99919810.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
