### ISSUE TITLE
dTRAM and WHAM with more than one bias

### ISSUE THREAD

**Issue by rekbet** [markovmodel/PyEMMA#1444]
I have run umbrella sampling simulations of a dimer and I would like to use the pyemma software to apply WHAM and dTRAM in order to unbias them. I have applied a bias on the distance between the monomers, and two additional biases on two dihedral angles to keep the dimers in place. These additional biases have a constant value and a constant force, and therefore only adds a contribution to the full biased energy. I have used plumed to run the simulations and have printed all the full bias energies to a data file.
I have already followed three of the tutorials from the website and the 2017 workshop, and have succesfully gotten WHAM to work using the estimate_umbrella_sampling function. However, as far as I can see, it is only possible to use one bias in this method as it uses the trajectories as input.
Is it possible to use the pyemma software with more than one bias, and if so, how would you suggest that I best use it?

**Comment by fabian-paul** [comment]
Hi,

estimate_umbrella_sampling allows to specify multi-dimensional biases. The function was meant for multi-dimensional US but simpler cases are also supported. Just pass in the collective variable time series for the two dihedrals as the `us_trajs` argument. All time series have to be combined in a specific format (numpy arrays with the time dimension in the first index, see below). The `us_centers` will have to contain a list of lists as shown below:
```Python
us_trajs = [ np.array([us_coordinate_traj_1, dihedral_1_traj_1, dihedral_2_traj]).T, ... ]
us_centers = [ [us_center_used_in_traj_1, dihedral_1_center, dihedral_2_center], 
               [us_center_used_in_traj_2, dihedral_1_center, dihedral_2_center]]
```
And similarly for us_force_constants. 

Just as warning: if you want to use dTRAM or WHAM, you will also have to discretize the two dihedrals finely. This could be serious limitation and the reason why multidimensional US is typically not used.

I know that this is not the question you asked, but I would advise a different strategy. I might be better to run dTRAM/WHAM with the 1-D coordinate and unbias the two dihedrals afterwards. This will only work if there is no unbiased data in dTRAM (i. e. simulations that were run without restraints on the dihedrals). If you must absolutely unbias all coordinates within dTRAM/WHAM (for instance because you have some completely unbiased trajectories) the better compromise might be to use TRAM/MBAR since then at least the discretization step will be less critical.

To unbias after running dTRAM/TRAM/WHAM/MBAR, you can grab the `stationary_distribution_full_state` property for the resulting dTRAM/WHAM object and multiply it by exp(dihedral_bias_energy_in_kT_per_cluster) or grab the the `pointwise_free_energies` property for the resulting TRAM/MBAR object and compute exp(-pointwise_free_energies+dihedral_bias_in_kT_per_frame).

Best,
Fabian

**Comment by rekbet** [comment]
Thank you for your answer. Would it be possible to get you to elaborate on the part after having run dTRAM/WHAM with the 1-D coordinate? I can calculate the bias energy for the dihedrals for each frame, but I am not sure what you mean by pr. cluster. Would that mean that the biased energies within a cluster should be added together or is it an average over the frames of the clusters? And how would I then add them to the PMF?
I'm also not exactly sure what it is that I get from the stationary_distribution_full_state property.

**Comment by fabian-paul** [comment]
That's a good question. The bias energies per cluster are actually hidden to the user when going through the `estimate_umbrella_sampling` API. Under the hood, this calls [pyemma.thermo.dtram](http://www.emma-project.org/v2.5.2/api/generated/thermo-api/pyemma.thermo.dtram.html), which needs a `bias` parameter. This is an array with the bias energy for every combination of discrete state  (aka cluster) and themodynamic state (aka umbrella). So even though you input biases for every conformation, they get averaged within each state when you select dTRAM or WHAM as an estimator. The values are not averaged if you select TRAM or MBAR. Averaging the bias energy can be a bit dangerous, if the discrete states are so coarse that the bias energies varies substantially inside a single discrete state. That's why dTRAM and WHAM are only recommended for "simple" situations, like 1-D umbrella sampling. In a parallel discussion thread @yunhuige and @vvoelz have come up with a superior way of doing the averaging by running MBAR for every discrete state separately. I don't know if they have coded anything that can be used easily.

Thinking about the problem again, I would probably convert back all the per-state quantities that come out of dTRAM/WHAM to per-conformation quantities and try to perform as much of the computation without discretization. This fits nicely with dihedral unbiasing after running dTRAM/WHAM. Say you have run dTRAM and saved the results into the variable `dtram`.
Then I would determine the per-conformation reweighting factors and do the dihedral unbiasing in one go:
```Python
total_counts = dtram.state_counts_full.sum(axis=0)
reweighting_factors = [[dtram.pi_full_state[s]/total_counts[s]*np.exp[dih_bias]  for s, dih_bias in zip(dtraj, dih_bias_traj)] for dtraj, dih_bias_traj in zip(dtrajs, dih_bias_trajs)]
```
The reweighting factors can then be used together with some observable to compute unbiased expectation values. The typical example of this would be to compute a histogram of some observable while using reweighing
```Python
matplotlib.pyplot.hist(x=np.concatenate(observable_trajs), weights=np.concatenate(reweighting_factors))
```

You can read a bit more on the theory (especially when applied to simple cases, like a single bias) in my [dissertation](https://publishup.uni-potsdam.de/opus4-ubp/frontdoor/deliver/index/docId/40427/file/paul_diss.pdf) I think your case is covered by the equations on page 52.

Fabian

**Comment by rekbet** [comment]
Hello again

Thank you very much for your explanation. We have now tried a number of different things, and I have a couple of more questions to ask.
When I try your first suggestions, in which I simply give a multidimensional input to pyemma, I define the centers as you say:
```javascript
us_centers = [ [us_center_used_in_traj_1, dihedral_1_center, dihedral_2_center], 
               [us_center_used_in_traj_2, dihedral_1_center, dihedral_2_center]]
```
However, the output from coordinates.assign_to_centers, is an array in the shape (24, 100001), since I have 24 umbrella sampling simulations and 100001 data points in each. I was hoping you could explain this output, since I would expect it to have the shape (24, 100001, 3) as it would have been dicretized to all three centers. I can see that this output is different from the one obtained from only giving the distances as input so it must still somehow include the dihedrals?

Moreover, when I calculate the PMF, I can see that my first free energy is 0. This is not a result I have gotten from any of the other methods, I have attempted. Is there an obvious reason for this?

For reference, these are my free energy values and my distances:
```javascript
wham_eq.free_energies = [  0.          76.74148201  64.5367184   61.88479677  60.42972298
  62.11338807  64.90775981  66.59911451  71.7910183   78.57740332
  87.51442644  97.11300095 100.79040076 102.27323577 105.3300036
 106.35928772 105.86195549 106.4081725  107.84453198 110.57898064
 110.96966073 111.03785651 110.83445714 111.76856926]
centers[1:] = [2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.75, 3.85, 3.95, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0]
```

**Comment by fabian-paul** [comment]
Sorry for the long delay. 
The question that you are asking actually gets asked a lot. The answer is that "cluster centers" and "umbrella centers" are quite different objects in PyEMMA. "cluster centers" correspond to the bins when using WHAM.  With the other methods dTRAM/TRAM/MBAR, cluster centers no longer correspond exactly to bins but rather to MSM microstates.
Like when constructing an MSM, the dimension of the space that you cluster is never reflected in the output of `assign_to_centers` or in `cluster_kmeans`. Instead everything just turns into a sequence of integers (the bin index, if you like). Of course to interpret the results, you would have to undo this mapping.
From what I've understood, you create the discrete trajectories by assigning to the umbrella centers. I think it is better to cluster the data into a slightly higher number of microstates (I would at least chose number of microstates > 2 number of umbrella centers). When using WHAM, the number of microstates corresponds to the number of bins. I would recommend to cluster with `cluster_regspace` and pass the output as the `us_dtrajs` (and possibly the `md_dtrajs`) parameter.
