### ISSUE TITLE
Why is the free energy landscape re-weighted using the stationary probabilities from the MSM?

### ISSUE THREAD

**Issue by eric-jm-lang** [markovmodel/PyEMMA#1460]
Hi,

I have what is probably a very basic question, but I do not seem to find a satisfactory answer.

In the `00-pentapeptide-showcase` tutorial, after calculating  the stationary distribution the free energy landscape is calculated by re-weighting the trajectory frames with stationary probabilities from the MSM.

Why is it re-weighted? Why isn't the free energy calculated from all the trajectory frames (obtained from classical MD) used? Is it a way to account for some sort of auto-correlation between frames? Or something else? My feeling was that the free energy obtained from unbiased simulation didn't require any re-weighting, is that incorrect?

Many thanks in advance!

**Comment by thempel** [comment]
It's a way to account for off-equilibrium sampling. The empirical distribution of your data only corresponds to the equilibrium distribution if your data is sampling global equilibrium. I.e. in the limit of infinite data, you can calculate the free energy just from the histogram. In the case of finite data, we reweigh the free energy landscape by making use of the equilibrium probability estimates that we get from the MSM. 

One example would be that you have a lot of trajectories that all start in the same basin of the free energy landscape. As long as these trajectories are not "infinitely" long, the histogram will always be biased towards that basin that you used as the starting point. MSMs account for that because they are based on counting transitions.

**Comment by eric-jm-lang** [comment]
Hi Tim,
Thanks a lot for your reply. I understand the reason of the re-weighting.
Thanks again!
