### ISSUE TITLE
source() fails to error on passing an array vs. list of trajectories // featurizer is only allegedly optional

### ISSUE THREAD

**Issue by rafwiewiora** [markovmodel/PyEMMA#1466]
So, finally after all these years I get to complain about your treatment of lists vs numpy arrays as input :D This might end up being my strongest memory from my PhD -- how every single damn time I try to calculate an MSM, I forget that PyEMMA will not let me just pass dtrajs as `dtrajs = np.load('dtrajs.npy')` but I gotta do `list(dtrajs)` -- I beg you, tell me why you can't just do this for me. 

But anyways, we're finally here because things got even more stupid. At least, with the above, I get an error. But, I do not get one if I try to use a numpy array with `pyemma.coordinates.source()`:

`data = pyemma.coordinates.source(np.array(['run0-clone0.h5', 'run0-clone1.h5']))` - NO ERROR and it returns a reasonably looking object:

```
DataInMemory(data=[array([['run0-clone0.h5'],
       ['run0-clone1.h5']], dtype='<U14')], chunksize=4793490)
```

which I can pass to say clustering and get an error that wastes the next few hours of my life:

```
cluster = pyemma.coordinates.cluster_kmeans(source, metric='minRMSD')   

ValueError: min_rmsd_metric is only implemented for input data with a dimension dividable by 3.
```

or 

```
cluster = pyemma.coordinates.cluster_kmeans(source)      

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Fun. `load()` doesn't have this problem:

```
data = pyemma.coordinates.load(np.array(['run0-clone0.h5', 'run0-clone1.h5']))

ValueError: unsupported type (<class 'numpy.ndarray'>) of input
```

Now problem number 2. This is my first time using RMSD clustering for a long time, and hence loading 3D coords. rather than some featurization, so here we are. Documentation states that in `source()` and `load()` the `features` are optional. What that tells me is that if I don't pass a featurizer, I load in 3D coords. Let's see:

```
data = pyemma.coordinates.load(['run0-clone0.h5', 'run0-clone1.h5'])                                                                                                 

~/anaconda3/envs/super_clean/lib/python3.7/site-packages/pyemma/coordinates/data/_base/datasource.py in filenames(self, filename_list)
    147                 import itertools, operator
    148                 res = {}
--> 149                 for dim, files in itertools.groupby(zip(ndims[sort_inds], filename_list[sort_inds]),
    150                                                     operator.itemgetter(0)):
    151                     res[dim] = list(f[1] for f in files)

IndexError: index 3 is out of bounds for axis 0 with size 2
```

I don't know what to say to this, but it's very far away from 'maybe you forgot to pass a featurizer'. 

Am I doing something stupid here? I'm like I gotta be, many other people would've caught these things before and they would've been corrected, they're so simple and at the start of the pipeline.

**Comment by clonker** [comment]
Let me try to address your comments.

1.  `dtrajs = np.load('dtrajs.npy')` but I gotta do `list(dtrajs)` strongly depends on what kind of things you stored in your npy file. Since its name is `dtrajs` rather than `dtraj` I assume it is a list of arrays? In that case the list gets converted to an array while you do `np.save('dtrajs.npy', dtrajs)`, i.e., upon loading you get an array of shape `(n_dtrajs, L)` which is going to be interpreted as `n_dtrajs` frames with `L` dimensions. If you want it to be recognized as `n_dtrajs` trajectories of length `L` then you have to cast it to a list. There is no other way of deciding whether one or the other (list of dtrajs or array of length dtrajs) is meant otherwise. Hence convention: multiple dtrajs are identified with lists of trajectories (which then can be ndarrays)
2. `data = pyemma.coordinates.source(np.array(['run0-clone0.h5', 'run0-clone1.h5'])` so this is a curious one. when you look closely at your output you see that the `dtype` of  the `DataInMemory` object is `<U14`. So the array is an array containing strings (unicode sequences) which are interpreted .......somehow within pyemma and clustering etc. Again, multiple trajectories are identified by giving it a list, i.e.,  `data = pyemma.coordinates.source(['run0-clone0.h5', 'run0-clone1.h5'])` should have the desired effect. I agree though that in the DataInMemory reader we could do more strict type-checking so that only numeric types are allowed.
3. For `load(...)` things are different because it tries to load everything into memory anyways instead of streaming it from file. So here it fails immediately if you dont give it a `list` but an `ndarray`.
4. Can you post the full stacktrace? Also what kind of data exactly is in these `h5` files? 
  - If these are raw hdf5 files, you can give it a selection string to select the dataset you want to load from it. Per default it is `selection='/*'`, meaning that everything will be loaded. It is given as a regular expression. Eg. `/group1/.*/my_dataset` will selection all 'my_dataset' in group1 no matter which kind of sub-groups these may belong to.
  - If these are actually molecular dynamics trajectories, you can try passing the filename also into the `top` argument as `h5` files then contain not only trajectory but also topology.
