### ISSUE TITLE
Make MDFeaturizer a scikit-learn type class

### ISSUE THREAD

**Issue by RobertArbon** [markovmodel/PyEMMA#1478]
Hi folks, 

this is a feature request that I'm happy to submit a PR for - I just want to know it's something you'd be happy with before I go and do it as it will take me a medium amount of time. 

How do you feel about having  MDFeaturizer fit the scikit-learn pattern?  The convenience api wouldn't change, but under the hood you would get this pattern: 

```
feat = MDFeaturizer(top=pdb, features = ['backbone_torsions'])
X = feat.fit_transform(trajs)
``` 

MDFeaturizer would inherit from the scikit-learn base estimator. 

Benefits would be fit the API pattern of the other classes that 'expert' users might want to use, with for example, Scikit-learn or Osprey (my use-case).

**Comment by clonker** [comment]
Hey, while I do like the compatibility advantages I don't really think that specifying features in the form of strings is convenient. To use its current state with scikit-learn/osprey you might want to just monkeypatch the instances. What do you think?

**Comment by RobertArbon** [comment]
OK, cool. I think you're right - it should be easier just to dump MDFeaturizer in a sklearn estimator wrapper at run time (if that's the kind of thing you mean). 

Out of interest - why do you not think it convenient?  Is it because it introduces another layer between user and code that needs to be maintained?

**Comment by clonker** [comment]
Yeah that is what i meant. :slightly_smiling_face: 

Wrt defining features via strings: yes exactly, we'd have to maintain the mapping feature name -> feature function and also take care of wrong/unsupported inputs. It might also be unfavorable when we want to rename/remove/replace something, deprecating function calls seems more straightforward than specific combinations of constructor inputs.
From a user's point of view I think it is almost always more convenient to have methods in such a case because then there is autocompletion and also documentation directly bound to the method itself.

**Comment by RobertArbon** [comment]
Ah ok.  Yes, ok, I get it. Thanks for the input.
