### ISSUE TITLE
Can enhanced sampling MD data be used for MSM analysis?

### ISSUE THREAD

**Issue by lucl13** [markovmodel/PyEMMA#1481]
Hi all,

Enhanced sampling is one of the important tool to traverse the phase space as much as possible. However, one of the biggest disadvantage is it will destroy the Boltzmann distribution due to the probability increase of some states which should have lower probability. In this case, it that correct to use these enhanced sampling MD data to construct MSM and do further analysis? Or MSM will rebuild the energy landscape by initial distribution and transition Matrix? 
 
What kind of the MD data could be used for MSM analysis? Is that reasonable to use manually enhanced sampling MD data (using convention MD and extra the rare states, which were further used as structure seed for second round sampling) ?

I am so confused.  Could anybody give some suggestion or recommendation of related paper? Looking forward to your kind reply. Thanks in advance. 

Best,
Chenlin

**Comment by thempel** [comment]
You are referring to methods such as adaptive sampling that e.g. seed simulations from rare states of the an existing MD dataset. MSMs can be used here because they are based on estimating conditional probabilities, i.e. it is explicitly not a histogram (a histogram would be biased here, as you are saying). In general, the standard MSMs/HMMs should be estimated in one statistical ensemble, i.e. your MD data must have been run under the same physical conditions (e.g. at the same temperature). I think that @marscher's pyemma paper [10.1021/acs.jctc.5b00743] could be a good starting point as many different methods are summarized with their use-cases.

**Comment by lucl13** [comment]
Understood. Thanks for you kind reply.
