### ISSUE TITLE
pyemma slow

### ISSUE THREAD

**Issue by lazylizzard99** [markovmodel/PyEMMA#1485]
Thanks for submitting an issue!
I have souce object takes very long to compile!! I safe source.save('source')., I load from disk, takes 15 again. Why?
soure=pe.load('source')
Here's a quick checklist in what to include:

- [  ] Include a detailed description of the bug or suggestion
- [ no] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
- [ 2.5.7] PyEMMA version and operating system versions
- [ ] Minimal example if possible, a Python script, zipped input data (if not too large)

**Comment by clonker** [comment]
Hi @lazylizzard99! This is very hard to say if you don't provide us with some more information. Are you working on a NFS? What kind of model are we talking about? Can you provide us with a snippet that reproduces the slow behavior?

**Comment by lazylizzard99** [comment]
I not sure why is so complicated. Is not invalid. Last line is problem.
```
dir="data"
dir2="trajectorys"
dir5=[ ]
for n, i in zip(enumerate(range(100)),range(100)):
    n = n[0]
    dir6=[ ]
    if n<10:
        dir3 = dir+'/'+dir2+'/'+'trojectaries0'+i.__str__( )
    if n>10:
        dir3 = dir+'/'+dir2+'/'+'trojectaries'+i.__str__( )
    dir3=dir3+'/'
    for n, i in zip(enumerate(range(33)), range(100)):
        dir4=dir3+'t'+n[0].__str__( )
        if i > 33:
            break
        dir4=dir4+'.xtc'
        dir6.append(dir4 )
    dir5.append(dir6)
import pyemma
pe=pyemma
sorce=pe.coordinates.source(dir5, top='new_final6.pdb')#take 15 min
sorce.save('pyemma')
soure=pe.load('pyemma')#15 min why??
```

**Comment by clonker** [comment]
This takes a while because you are indexing 3300 trajectory files, in particular 100 trajectories with 33 trajectory fragments each (are the fragments intended or is this meant to be a flat list?).
The data source objects gather statistics (such as number of frames per trajectory), which is currently not stored inside the saved file. Depending on file format this can take a while, especially XTC can take a while to load. There is a cache for these kinds of things but perhaps it is switched off for you or it is in fact something else causing the load time. Could you check your [pyemma configuration file](http://www.emma-project.org/latest/Configuration.html)?

Thank you for providing us with a snippet that demonstrates your problem.

**Comment by thempel** [comment]
Thanks for your nice minimal example. As far as I understand, what makes this operation slow is that the number of frames per trajectory is computed by temporarily loading each xtc file (?). What I don't understand is why the results are not written to disk when the `source` object is saved. I can definitely confirm that for large datasets in xtc format, loading the source object by calling `pyemma.load()` can be very slow.

**Comment by clonker** [comment]
Yes the length of a XTC file can only be obtained by streaming through it iirc. This does not mean that the whole file is loaded into memory at once but rather chunks of it, counting the frames. The results of this are not written to disk because the required fields are not marked as such (serializable, that is) in the respective class definitions. This can be improved obviously, although I thought that the Caching architecture would take care of it by writing this information into a local sqlite database.

**Comment by lazylizzard99** [comment]
Don't think is cached. 

[pyerra.txt](https://github.com/markovmodel/PyEMMA/files/5886234/pyerra.txt)

**Comment by peterpeter465** [comment]
I have same problem with being slow. How do I where?

**Comment by lazylizzard99** [comment]
Pyerra is slow change my mind. I buy new hard disk, now faster.
