### ISSUE TITLE
Running a simulation to create data for PyEmma

### ISSUE THREAD

**Issue by phisanti** [markovmodel/PyEMMA#1487]
Hi,

My question is rather theoretical and more related to the MD previous step rather than the MSM analysis. I am currently designing a simulation to study the opening/closure of a protein. We believe this happens through the change in location of an arm-loop that acts as the gate. We also think that such a process requires 200-500ns. Then, I have read that MSM allows to run "millisecond" simulations, but at the same time, I see in the docs that MSM is not a simulation running tool, rather an analysis tool. Thus, I was wondering:

1- Is it true that MSM helps to achieve millisecond simulations? If so, how does it happens?
2- Assuming I am running my simulation on openMM, would someone help me with some pseudo-code to design the MD data before the MSM step. I am sure it should be something like: 

```python
import libraries

inputs = read_inputs(args.inpfile)
params = read_params(args.toppar)
for i in 500:

system = inputs.createSystem(params)
integrator = LangevinIntegrator(inputs.temp*kelvin, inputs.fric_coeff/picosecond, inputs.dt*picoseconds) 
simulation.step(inputs.nstep) # Here I think the key is running many small simulations, such as 500 of 1 ns sim to create the sampling space for MSM
```

Thanks in advance for your help, and sorry if this is a blunder. I am new in MD, just learning by doing!

**Comment by thempel** [comment]
Hi Phisanti, 
MSMs are a low-rank approximation to the transfer operator of the dynamics. I.e. if you learn an MSM from a small set of simulation data, which contains the dynamics of millisecond processes, you can use that MSM to generate further data (within that approximation). In practice that requires that the sampling covers the slow process, e.g. because a "smart" sampling scheme was used (such as adaptive sampling). A simulation in the MSM framework usually refers to applying the estimated MSM transition matrix to a probability distribution, which propagates that distribution in time. Since the MSM is a low-rank approximation, that usually means that you e.g. simulate the trajectory of a very slow observable which you might not have sampled a full continuous trajectory. (Example: If you have two trajectories, a: [1, 1, 2, 2, 1, 1] and b: [2, 3, 2, 3, 2, 3], the MSM will be able to simulate a trajectory between all states 1, 2 and 3 with the correct dynamics even if that was never observed inside one single MD trajectory.)

Since to my knowledge, openMM does not parallelize well with multiple systems on a single GPU, your code is probably very slow. If you want to run on multiple GPU devices, you can just use a regular openMM script (I recommend the [openMM builder](builder.openmm.org)) and run it on multiple parallel instances. You can analyze the trajectories with pyemma later. If you want a more sophisticated tool for adaptive sampling, there is for example the [adaptive sampling package](https://github.com/markovmodel/adaptivemd). An interesting read about adaptive sampling strategies might be this paper: https://doi.org/10.1063/1.5053582

Another comment about your code: Assuming that you only have one single starting structure like a crystal structure, I would prefer a single 500 ns simulation over 500 x 1 ns simulations. The reason is that 1 ns simulations might just all sample the same long-lived state because 1 ns is really short. 

Hope that helps.
