### ISSUE TITLE
Errors in the pyemma jupyternotebook tutorials

### ISSUE THREAD

**Issue by e-richter** [markovmodel/PyEMMA#1492]
Hi all,
during my work with pyemma and looking into the documentation and jupyter notebook tutorials I've seen that there are error messages on the website. For example here: http://emma-project.org/latest/tutorials/notebooks/04-msm-analysis.html#, but also in later chapters.

Cheers,
Emilius

**Comment by clonker** [comment]
Hi, thank you for reporting this! I need to check the serialization routines.

**Comment by andresilvapimentel** [comment]
I am trying to run the tutorial notebook "Analyzing umbrella sampling simulations with PyEMMA" on google colab, but I am getting the following error message:

ValueError                                Traceback (most recent call last)
<ipython-input-7-88b86b731c99> in <module>()
     12 # Load precomputed simulation data
     13 data = np.load('adw_us.npz', encoding='latin1')
---> 14 us_trajs = [np.asarray(l, dtype=np.float64).reshape((-1, 1)) for l in data['arr_0'].tolist()]
     15 us_centers = data['arr_1'].tolist()
     16 us_force_constants = data['arr_2'].tolist()

1 frames
/usr/local/lib/python3.7/dist-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
    725         # The array contained Python objects. We need to unpickle the data.
    726         if not allow_pickle:
--> 727             raise ValueError("Object arrays cannot be loaded when "
    728                              "allow_pickle=False")
    729         if pickle_kwargs is None:

ValueError: Object arrays cannot be loaded when allow_pickle=False

I made few changes in the original notebook as follows:
# uploading the adw_us.npz file
from google.colab import files
uploaded = files.upload()

%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pyemma
mpl.rcParams['font.size'] = 12
mpl.rcParams['axes.labelsize'] = 15
mpl.rcParams['xtick.labelsize'] = 12
mpl.rcParams['ytick.labelsize'] = 12
mpl.rcParams['legend.fontsize'] = 10

# Load precomputed simulation data

# HERE WAS THE ONLY CHANGE
data = np.load('adw_us.npz', encoding='latin1')
# I REMOVED THE ./DATA/ DIRECTORY HERE BECAUSE I UPLOADED THE adw_us.npz FILE IN THE PRECIOUS SECTION. 

us_trajs = [np.asarray(l, dtype=np.float64).reshape((-1, 1)) for l in data['arr_0'].tolist()]
us_centers = data['arr_1'].tolist()
us_force_constants = data['arr_2'].tolist()
md_trajs = [np.asarray(l, dtype=np.float64).reshape((-1, 1)) for l in data['arr_3'].tolist()]
centers = data['arr_4']
reference = data['arr_5']

Could you tell what is wrong in this notebook, please? Thank you in advance. Andre Pimentel

**Comment by thempel** [comment]
Does this error occur in the online version of the PyEMMA documentation (which is the topic of this issue) or just in your google colab? 

If I understand this right, your error is `ValueError: Object arrays cannot be loaded when allow_pickle=False`. Have you tried just setting that flag?
```python
data = np.load('adw_us.npz', encoding='latin1', allow_pickle=True)
```

**Comment by andresilvapimentel** [comment]
I did not tried the on line version, but I tried the flag allow_pickle =
true and did not work it.

Em qua, 17 de mar de 2021 05:41, Tim Hempel ***@***.***>
escreveu:

**Comment by clonker** [comment]
Hi @andresilvapimentel, could you be a bit more specific than did not work? Also I suspect this is not really an issue related to PyEMMA but rather related to your general setup and NumPy(version). In any case, I could reproduce the error and subsequently fix it by adding the `allow_pickle=True` keyword argument.
Please, try again and perhaps also restart your notebook kernel. For the future we would appreciate if you add a new issue rather than hijacking an existing one, helps us keeping everything organized :+1:
