### ISSUE TITLE
varify Markov model built by Umbrella sampling with PyEMMA

### ISSUE THREAD

**Issue by wyb2021** [markovmodel/PyEMMA#1517]
Hello there,

I have a quick question about this tutorial:

http://www.emma-project.org/latest/legacy-notebooks/methods/multi_ensemble/doublewell/PyEMMA.thermo.estimate_umbrella_sampling_-_asymmetric_double_well.html

So I have biased samplings (umbrella sampling ) and unbiased sampling trajectories. Based on my understanding, we usually use two ways together to verify our Markov model: one is the implied timescales and the other one is the CK test. However, CK test is only for unbiased trajectories. If I combined biased and unbiased trajectories together to build my own Markov model, how could I verify my Markov model beside the implied timescales method? 

Thanks for your time.

**Comment by clonker** [comment]
Hi, in principle I think it is possible but currently not implemented. In the end what the ck-test does is verify that two covariance matrices coincide:

- it estimates transition matrices `P(n*tau)` for `n=1,...,k` and computes `<P g_i, f_j>`
- it predicts `<P^n(tau) g_i, f_j>`

... where `P(.)` refers to the transition matrix of your MSM at a certain lagtime.

Because there typically is not enough data to generate and parametrize a meaningful test over the full discrete state space, a pcca course graining is performed beforehand and the covariance matrices are evaluated on the coarse-grained space. For MSMs we typically take `f=g=p_0`, where `p_0` is the stationary distribution in a metastable set of states.
With this you should be able to implement it "by hand".
