### ISSUE TITLE
uniform time clustering fails for k > chunksize

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#213]
added test case to reproduce. This should be catched somehow.

**Comment by marscher** [comment]
Do we need to store multiple chunks if k gets bigger? Have not really looked into it. @franknoe you wrote this algo, what do you sugguest?

**Comment by franknoe** [comment]
There should be no such problem, i.e. it should be possible to fix it. I 
haven't looked into it yet because this clustering method is not really 
used, it was just an example impl in the prototype.

Don't worry about it for now. I'll do it if there's time. If not, we can 
remove it for now.


Am 10/04/15 um 12:13 schrieb Martin K. Scherer:
>
> Do we need to store multiple chunks if k gets bigger? Have not really 
> looked into it. @franknoe <https://github.com/franknoe> you wrote this 
> algo, what do you sugguest?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/213#issuecomment-91506015>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
fixed
