### ISSUE TITLE
ReaderInterface._add_array_to_storage is unsafe

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#216]
l. 108:         self._data.append(array)
will fail unless _data is initialized in subclass. Currently this function is only used in DataInMemory.
Should probably initialize _data in the superclass to guarantee consistency.

**Comment by marscher** [comment]
Am 11.04.2015 um 02:25 schrieb Frank Noe:
> l. 108: self._data.append(array)
> will fail unless _data is initialized in subclass. Currently this
> function is only used in DataInMemory.
> Should probably initialize _data in the superclass to guarantee consistency.
Not every reader uses a storage (CSVReader does not), but holding an 
empty list is not very expensive (but also a bit confusing).


This method is used in DatainMemory and the new NumpyFileReader. Both 
classes initialize their storage. Since it is a private method, why 
should I build in safe guards? If one uses the __private__ add_array 
method and forgot to init the storage, the resulting AttributeError will 
be more than clear.

If we want to make it super idiot proof, we can add the storage as an 
required argument of the method.

**Comment by franknoe** [comment]
I understand that it works in the current construction, but like that 
one has to understand the internal logic of several objects in order to 
extend them correctly plus it creates a code check error because from 
the viewpoint of DataInMemory there is no _data available.

Am 11/04/15 um 11:53 schrieb Martin K. Scherer:
> Am 11.04.2015 um 02:25 schrieb Frank Noe:
> > l. 108: self._data.append(array)
> > will fail unless _data is initialized in subclass. Currently this
> > function is only used in DataInMemory.
> > Should probably initialize _data in the superclass to guarantee 
> consistency.
> Not every reader uses a storage (CSVReader does not), but holding an
> empty list is not very expensive (but also a bit confusing).
>
>
> This method is used in DatainMemory and the new NumpyFileReader. Both
> classes initialize their storage. Since it is a private method, why
> should I build in safe guards? If one uses the __private__ add_array
> method and forgot to init the storage, the resulting AttributeError will
> be more than clear.
>
> If we want to make it super idiot proof, we can add the storage as an
> required argument of the method.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/216#issuecomment-91810411>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
fixed by 1d727bcd5e2d6d53c9904d583abb6ced2bf5b56e (not yet pushed)
