### ISSUE TITLE
rename msm.io to avoid shadowing python package io

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#218]

**Comment by marscher** [comment]
since this brakes the api, we should do this in 1.3 and deprecate it somehow (I currently do not know what is the best practice to deprecate a package name).

But actually the issue of shadowing is not a big deal, since it only affects imports one level above "io". So in principle we can not import the builtin.io at level of the msm package. In my opinion this only creates work and does not solve any real problem.

**Comment by franknoe** [comment]
Moved to msmtools
