### ISSUE TITLE
No module named input after update

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#219]
I get the following error now:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-a96309e61bfe> in <module>()
      1 feat.add_distances_ca()
----> 2 data = coor.input(traj, feat)

AttributeError: 'module' object has no attribute 'input'

code is:
```
import pyemma.coordinates as coor
import matplotlib.pylab as plt
%pylab inline
top = 'data/a10_ff99/no_water.gro'
traj = 'data/a10_ff99/md_production1.xtc'
feat = coor.featurizer(top)
feat.add_distances_ca()
data = coor.input(traj, feat)
```

**Comment by franknoe** [comment]
Because input has been renamed to source (see last merge)

Am 11/04/15 um 15:01 schrieb ppxasjsm:
>
> I get the following error now:
>
> ------------------------------------------------------------------------
>
> AttributeError Traceback (most recent call last)
> in ()
> 1 feat.add_distances_ca()
> ----> 2 data = coor.input(traj, feat)
>
> AttributeError: 'module' object has no attribute 'input'
>
> code is:
>
> |import pyemma.coordinates as coor
> import matplotlib.pylab as plt
> %pylab inline
> top = 'data/a10_ff99/no_water.gro'
> traj = 'data/a10_ff99/md_production1.xtc'
> feat = coor.featurizer(top)
> feat.add_distances_ca()
> data = coor.input(traj, feat)
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/219>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by ppxasjsm** [comment]
ah yes sorry.
