### ISSUE TITLE
test_cluster (which only run test kmeans) runs for ~25 seconds

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#232]
is really necessary to have such an exhaustive test case? The whole test suite take this runtime before. Consider adding a slow attribute (so we can automatically exclude the super slow tests) and add some sane test example.

A testsuite should run in a few seconds to check if everything is intact.

**Comment by marscher** [comment]
same goes for the new tests for pca and tica. Are the input dimension that large and useful for a test? I'm getting grey and old waiting for results now.

**Comment by franknoe** [comment]
I think the problem is that the setUp takes mildly long and then there 
are a ton of test functions.
Each of them seems to be executed independently and create a new object, 
so that adds up.

Is there a way to avoid this and have the setUp stuff only done once?

Am 13/04/15 um 01:50 schrieb Martin K. Scherer:
>
> is really necessary to have such an exhaustive test case? The whole 
> test suite take this runtime before. Consider adding a slow attribute 
> (so we can automatically exclude the super slow tests) and add some 
> sane test example.
>
> A testsuite should run in a few seconds to check if everything is intact.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/232>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
same comment like before. It's not really a large example. Let's discuss 
later.

Am 13/04/15 um 02:29 schrieb Martin K. Scherer:
>
> same goes for the new tests for pca and tica. Are the input dimension 
> that large and useful for a test? I'm getting grey and old waiting for 
> results now.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/232#issuecomment-92156706>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
yes setUpClass is the function which gets called only once.
