### ISSUE TITLE
test_pca fails randomly (succeeds most of the time)

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#257]
# 
## FAIL: test_cov (pyemma.coordinates.tests.test_pca.TestPCAExtensive)

Traceback (most recent call last):
  File "/home/travis/build/markovmodel/PyEMMA/pyemma/coordinates/tests/test_pca.py", line 50, in test_cov
    assert(np.max(self.pca_obj.cov - cov_ref) < 3e-2)
AssertionError

**Comment by franknoe** [comment]
I have noticed this too. We have two options: 1) Set the tolerance 
higher because the test is using a random trajectory, 2) Store the 
trajectory and set the tolerance tighter. This example is taken from 
msmdocs:

And the main point is that the first component is approximately right.

Both solutions would be OK

Am 16/04/15 um 18:35 schrieb Martin K. Scherer:

> ```
> FAIL: test_cov (pyemma.coordinates.tests.test_pca.TestPCAExtensive)
> ```
> 
> Traceback (most recent call last):
> File 
> "/home/travis/build/markovmodel/PyEMMA/pyemma/coordinates/tests/test_pca.py", 
> line 50, in test_cov
> assert(np.max(self.pca_obj.cov - cov_ref) < 3e-2)
> AssertionError
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/257.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Or we can generate the trajectory with a fixed seed, which we know to yield a traj working for this test. So we would avoid to store it

**Comment by franknoe** [comment]
Great idea!

Am 16/04/15 um 19:01 schrieb Martin K. Scherer:

> Or we can generate the trajectory with a fixed seed, which we know to 
> yield a traj working for this test. So we would avoid to store it
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/257#issuecomment-93785433.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
