### ISSUE TITLE
Transformer.get_output() fails for 1D data

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#270]
This happens for a CustomFeature which returns chunks in 1D.

Actually the testing coverage of Transformer is only 70% and especially the dimensions handling in get_output is only tested for slice type.

**Comment by fabian-paul** [comment]
I thought we agreed that internally the chain should use two-dimensional arrays only. How can the CustomFeature return 1D data?
Or am I wrong?

**Comment by marscher** [comment]
ok, that makes sense.

**Comment by franknoe** [comment]
I would graciously accept 1D arrays as inputs (as this corresponds to 
(Tx1)-matrices). I would format the output always as 2D.

Am 23/04/15 um 11:10 schrieb fabian-paul:

> I thought we agreed that internally the chain should use 
> two-dimensional arrays only. How can the CustomFeature return 1D data?
> Or am I wrong?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/270#issuecomment-95500917.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I will add some sanity checks in the Featurizer in case of user provided functions.

**Comment by franknoe** [comment]
OK, we should put some more effort in testing various cases here, as 
this is a central object. Since we have tests for subclasses I imagine 
that all the methods somehow get used in several tests, but we should 
more explicitly try to break it by testing varous forms of input.

Am 22/04/15 um 19:04 schrieb Martin K. Scherer:

> This happens for a CustomFeature which returns chunks in 1D.
> 
> Actually the testing coverage of Transformer is only 70% and 
> especially the dimensions handling in get_output is only tested for 
> slice type.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/270.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
sanity checks added.
