### ISSUE TITLE
coordinates.api.load/source enforces to pass topology, but not every format needs it.

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#272]
Currently mdtraj supports formats which enforces the user to specify a topology and some which ship their topology. The loaders for the latter raise, if they got passed a top keyword.

Question is how we should deal with that. For now we support only explicit topology formats.

A case for implicit topology is netcdf.

**Comment by franknoe** [comment]
We probably have to distinguish cases by file type. If the Exception 
raised is specific enough we could also try with top, catch the 
exception and then try again without top which would be more future 
proof in case if they decide to change the list of supported file types.

A related side-issue: it would be nice not to need a topology file if we 
just want to use Cartesian coordinates. Probably this would involve 
doing something on the mdtraj side, but perhaps we can also give mdtraj 
a fake topology.

Am 24/04/15 um 19:34 schrieb Martin K. Scherer:

> Currently mdtraj supports formats which enforces the user to specify a 
> topology and some which ship their topology. The loaders for the 
> latter raise, if they got passed a top keyword.
> 
> Question is how we should deal with that. For now we support only 
> explicit topology formats.
> 
> A case for implicit topology is netcdf.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/272.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
Do you have an example netcdf file which has an implicit topology? The formats with implicit topology are (according to the code of mdtraj) hdf5, pdb and lh5. These can simply be passed into the coordinates api like

``` python
source_lh5 = api.load(lh5md_file, top=lh5md_file)
```

without causing anything to raise. I think it even makes sense to pass them like this since they do contain the topology information and assuming one can give a fake topology for cartesian coordinates, one has a good distinction when to use the fake one (i.e., no topology / featurizer provided) and when to use something else. If it was just

``` python
source_lh5 = api.load(lh5md_file)
```

one would somehow have to decide whether to use cartesian coordinates or if this is a file with an implicit topology (and mdtraj currently does not maintain an accessible list of file formats which contain topology information).

**Comment by marscher** [comment]
it is not an issue, because it does not lead to a failure.
