### ISSUE TITLE
Careful refactor in MSM object for arguments "k=None, ncv=None"

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#296]
Find out if we can tune the MSM object such that both

```
    M.eigenvalues
```

and

```
    M.eigenvalues()
```

will work (we want to stay backward-compatible). If yes:
- apply the solution to eigenvalues, eigenvectors_left, eigenvectors_right and timescales. 
- introduce a function `set_eigendecomposition_params(k=None, ncv=None)` which sets these parameters object-wide.
- the functions () above will raise a deprecation warning, call that method and then return the attribute. 

This change goes directly into 1.2.1 _or_ into 1.3 (it is not an urgent issue)

**Comment by marscher** [comment]
This is not possible because in the class impl during attribute access we can not know whether the user wants to use the attribute (be not be confused, everything is an attribute) as a function (call it) or just use its value. If one refactors methods to properties, every usage has to be refactored too, there is no elegant way to solve this.

Only dark inspection hacks (looking forward in the code what is going to happen with the returned attribute) would make this possible and I strongly discourage such patterns.

**Comment by franknoe** [comment]
Ah that is a pity. Then we have to decide whether we want to break people's code rather sooner than later, or go along with a slightly inconvenient usage.
