### ISSUE TITLE
kmeans progress bar is misleading

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#326]
For k-means the progressbar immediately jumps to 95% or so and then stops. Probably the time is reported for reading the data (which is very fast), and then it waits for the relatively slow clustering. This is misleading. Can we call the individual iterations from python and then increase progress by iteration?

**Comment by marscher** [comment]
Your intuition is totally right. The actual cluster algorithm is not
being respected, since it runs completely on C-side and we would have to
perform callbacks into Python (which should be possible).

Back when we used Minibatch-Kmeans the progress bar was meaningful.
We can perform the call via passing the instance to C and lookup the
progress bar attribute.

**Comment by marscher** [comment]
since the algorithm has essentially three different parts:
1. gather data
2. initialization
3. iteration (for which we do not know a priori when it will converge)

it is difficult to estimate a total runtime. Of course we can add add
progress bar initialized to max_iter, but that may also be misleading,
since it might converge much earlier, if we already got a good estimate
for the centers.

**Comment by marscher** [comment]
logging seems to be more convenient solution then.

**Comment by franknoe** [comment]
We can do a progress bar for gathering the data and one for the 
iteration. Maybe the initialization also consists of going in cycles 
somehow - let's see what Moritz thinks

Am 26/05/15 um 16:31 schrieb Martin K. Scherer:

> since the algorithm has essentially three different parts:
> 1. gather data
> 2. initialization
> 3. iteration (for which we do not know a priori when it will converge)
> 
> it is difficult to estimate a total runtime. Of course we can add add
> progress bar initialized to max_iter, but that may also be misleading,
> since it might converge much earlier, if we already got a good estimate
> for the centers.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/326#issuecomment-105544855.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
@clonker noticed

**Comment by clonker** [comment]
About the initialization - kmeans++-init is indeed performed sequentially center by center so a progress bar can be done, the uniformly distributed version of init initialises by passing over the data once, i.e., the gathering-data progress bar would be sufficient there.

The iterations might still be reasonable as progress bar (with respect to max-iters), as it gives a worst-case information about the runtime..
