### ISSUE TITLE
[coordinates.tica] docstring for parameter data is incomplete...

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#330]
...it should note that not only np.ndarrays are OK, but also pyemma.coordinates.source objects

**Comment by franknoe** [comment]
Things of that magnitude - just do it rather than reporting an issue.

Am 26/05/15 um 18:47 schrieb Guillermo Pérez-Hernández:

> ...it should note that not only np.ndarrays are OK, but also 
> pyemma.coordinates.source objects
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/330.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
