### ISSUE TITLE
[docs] Ipython pentapeptide notebook displays funny in the docs

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#437]
I just had a browse through the ipython pentapeptide notebook and noticed that my browser (safari) displays one of the plots not correctly. 
Have a look a this:
![screen shot 2015-07-21 at 21 36 42](https://cloud.githubusercontent.com/assets/3668316/8811914/1043baee-2ff1-11e5-8ab0-5da1a42bc5e1.png)
I am assuming the '3' should be in the plot somewhere?

**Comment by franknoe** [comment]
That problem comes from the (random) direction of eigenvectors. I have 
corrected this already, but Martin needs to do something to push it to 
the website.

Am 21/07/15 um 22:41 schrieb ppxasjsm:

> I just had a browse through the ipython pentapeptide notebook and 
> noticed that my browser (safari) displays one of the plots not correctly.
> Have a look a this:
> screen shot 2015-07-21 at 21 36 42 
> https://cloud.githubusercontent.com/assets/3668316/8811914/1043baee-2ff1-11e5-8ab0-5da1a42bc5e1.png
> I am assuming the '3' should be in the plot somewhere?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/437.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ppxasjsm** [comment]
Ok!

**Comment by nsplattner** [comment]
The documentation is updated now.

**Comment by franknoe** [comment]
Thanks! Now we just need the pentapeptide notebook for download with the 
data.

Am 22/07/15 um 14:42 schrieb nsplattner:

> The documentation is updated now.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/437#issuecomment-123708142.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
