### ISSUE TITLE
attribute error in implied timescales

### ISSUE THREAD

**Issue by nsplattner** [markovmodel/PyEMMA#483]
Returning the implied timescales (current devel branch)  with get_timescales() exits with the following error message:

```
    its = implied_timescales.get_timescales()
  File "/storage/mi/nplattner/miniconda/envs/PyE_devel/lib/python2.7/site-packages/pyemma/msm/estimators/implied_timescales.py", line 249, in get_timescales
    return self._its[self._successful_lag_indexes, :]
AttributeError: 'ImpliedTimescales' object has no attribute '_successful_lag_indexes'
```

**Comment by franknoe** [comment]
Thank you, I'll check.

Am 05/08/15 um 15:35 schrieb nsplattner:

> Returning the implied timescales (current devel branch) with 
> get_timescales() exits with the following error message:
> 
> |     its = implied_timescales.get_timescales()
>    File "/storage/mi/nplattner/miniconda/envs/PyE_devel/lib/python2.7/site-packages/pyemma/msm/estimators/implied_timescales.py", line 249, in get_timescales
>      return self._its[self._successful_lag_indexes, :]
> AttributeError: 'ImpliedTimescales' object has no attribute '_successful_lag_indexes'
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/483.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
That should work once the timescales are estimated. Perhaps you are 
using it this way?

``` python
from pyemma import msm
its = msm.ImpliedTimescales(...)
```

that way you are just creating the object that must still be 
parametrized with

``` python
msm.estimate(dtrajs)
```

But I guess what you'd rather like to do is directly

``` python
msm.timescales_msm(dtrajs, lags=[1, 2, 3], ...)
```

Does that solve the problem? I think we should anyway have an 
understandable error message when trying to use the estimator before 
having estimated it, and I'll create an issue for that.

Am 05/08/15 um 15:35 schrieb nsplattner:

> Returning the implied timescales (current devel branch) with 
> get_timescales() exits with the following error message:
> 
> |     its = implied_timescales.get_timescales()
>    File "/storage/mi/nplattner/miniconda/envs/PyE_devel/lib/python2.7/site-packages/pyemma/msm/estimators/implied_timescales.py", line 249, in get_timescales
>      return self._its[self._successful_lag_indexes, :]
> AttributeError: 'ImpliedTimescales' object has no attribute '_successful_lag_indexes'
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/483.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by nsplattner** [comment]
I think this was the problem and now I understand the syntax. Thanks! 
This was slightly different in the previous version and therefore confusing. Having a more understandable error message would clearly help.

**Comment by franknoe** [comment]
Yes, compared to the previous version estimators only do their job when 
you explicitly ask them to. This is important for meta-algorithms like 
ImpliedTimescales. The way they are internally used is to create an MSM 
or HMM Estimator, feed them into the ImpliedTimescales object and that 
then runs the underlying estimator with different lag times. That way we 
can use the same code for many purposes.

Because we don't want the user to worry about this we have convenience 
functions at the package level, such as timescales_msm, which run the 
object construction and estimation. Generally, functions are lowercase 
and objects are uppercase. As a user you will usually want to run the 
lowercase stuff.

Am 05/08/15 um 17:28 schrieb nsplattner:

> I think this was the problem and now I understand the syntax. Thanks!
> This was slightly different in the previous version and therefore 
> confusing. Having a more understandable error message would clearly help.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/483#issuecomment-128039159.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by nsplattner** [comment]
O.k., that's  a nice concept.
