### ISSUE TITLE
[featurizer, ReaderInterface, Transformer ] make dimension() always a property? 

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#488]
I think it makes more sense. Agree?

**Comment by franknoe** [comment]
I agree. We have already discussed that for the dimension and also for a 
few other quantities in the MSM object. The problem is that this would 
break people's codes without improving much. We cannot have dimension as 
a property and dimension as a method at the same time, that means we 
cannot keep the function and deprecate it.

In sklearn they solved that problem by naming properties always with 
tailing underscore (e.g. dimension_ ), that way it's clear - once the 
user has understood the concept - what's a property and what's a 
function, and there are no name clashes between properties and methods. 
But I don't think that's a pretty solution, and I'm not convinced that 
this is an improvement for users that are not very proficient in python.

We should discuss how to generally handle these things before the next 
release. Let's leave this alone for now. No API changes in the next two 
weeks.

Am 06/08/15 um 12:32 schrieb Guillermo Pérez-Hernández:

> I think it makes more sense. Agree?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/488.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Got it

On 08/06/2015 03:15 PM, Frank Noe wrote:

> I agree. We have already discussed that for the dimension and also for a
> few other quantities in the MSM object. The problem is that this would
> break people's codes without improving much. We cannot have dimension as
> a property and dimension as a method at the same time, that means we
> cannot keep the function and deprecate it.
> 
> In sklearn they solved that problem by naming properties always with
> tailing underscore (e.g. dimension_ ), that way it's clear - once the
> user has understood the concept - what's a property and what's a
> function, and there are no name clashes between properties and methods.
> But I don't think that's a pretty solution, and I'm not convinced that
> this is an improvement for users that are not very proficient in python.
> 
> We should discuss how to generally handle these things before the next
> release. Let's leave this alone for now. No API changes in the next two
> weeks.
> 
> Am 06/08/15 um 12:32 schrieb Guillermo Pérez-Hernández:
> 
> > I think it makes more sense. Agree?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/488.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/488#issuecomment-128358959.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/
