### ISSUE TITLE
development install

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#560]
If I try and do a development install of pyemma, it will fail if I don't use:

```
conda install mdtraj
conda install bhmm
```

before the install:

```
python setup.py develop
```

I did this on a completely clean conda install and a completely clean pyemma checkout.

**Comment by marscher** [comment]
Would you please provide some details on what "fails" mean in this context? Actually the dependency tree can not be installed automatically, since mdtraj does not correctly depend cython (it just tries to import it and dies, if it is not there - but it could drag it in automatically). Because there is no clean way to influence the order of installation, we should either require the pip user to install cython or patch mdtraj such that it handles its dependencies properly.
