### ISSUE TITLE
rename ctor arg topology of MDFeaturizer back to topfile to preserve API

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#587]
we can just add another arg named topology, set topfile and topology to None and require at least one valid arg.

**Comment by marscher** [comment]
https://github.com/markovmodel/PyEMMA/commit/5c2c472f5e7f41bcaab4c838fa9fc0b43b398456

**Comment by franknoe** [comment]
what about using "top" as the new argument, as in mdtraj.

Am 26/10/15 um 17:01 schrieb Martin K. Scherer:

> we can just add another arg named topology, set topfile and topology 
> to None and require at least one valid arg.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/587.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
You're right. Lets name it so.

**Comment by marscher** [comment]
But, by changing the name to a new one, we'll brake the api. Is this desired?

**Comment by franknoe** [comment]
No, I don't intend to break the api. I suggest to keep topfile=None as a 
first argument, but to add the additional argument top=... One of the 
two is required and either a file or a Topology object is accepted. In 
principle the new argument has no effect - it is just a semantic thing 
because the user might find it confusing that "topfile" can also be an 
object.

Am 26/10/15 um 17:07 schrieb Martin K. Scherer:

> But, by changing the name to a new one, we'll brake the api. Is this 
> desired?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/587#issuecomment-151189065.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 26.10.2015 um 17:09 schrieb Frank Noe:

> No, I don't intend to break the api. I suggest to keep topfile=None as a
> first argument, but to add the additional argument top=...
> Keeping the rename from topology to topfile or renaming toplogy to top 
> is actually a api breaker. But IMHO it is a minor change and does not 
> require so much refactoring (maybe none at all, because people did not 
> name the argument during invocation).

**Comment by franknoe** [comment]
Bottomline - this was changed and then changed back, so the new version is the old version, and the API is therefore not impaired. I.e. we don't need to do anything.
