### ISSUE TITLE
Remove duplicate code in util

### ISSUE THREAD

**Issue by trendelkampschroer** [markovmodel/PyEMMA#638]
There seems to be some duplicate code in 

pyemma.util

and 

msmtools.util

we recently had to fix a bug in msmtools.util.statisics that needs to be copied over to pyemma. Would it be possible to move all submodules in pyemma.util that are also (partly) needed by msmtools to msmtools and import from msmtools in pyemma?

To be clear. I don't propose to completely move util from pyemma to msmtools. Both can have their own util modules. It would just be good to identify the functionality that is needed by msmtools and pyemma and have that residing in msmtools.

**Comment by marscher** [comment]
On 27.11.2015 11:38, Benjamin Trendelkamp-Schroer wrote:

> There seems to be some duplicate code in
> 
> pyemma.util
> 
> and
> 
> msmtools.util
> 
> we recently had to fix a bug in msmtools.util.statisics that needs to be
> copied over to pyemma. Would it be possible to move all submodules in
> pyemma.util that are also (partly) needed by msmtools to msmtools and
> import from msmtools in pyemma?

This would be a no brainer and would keep maintenance effort low. Since
PyEMMA already hard depends on msmtools, this does not introduce any new
deps. Haven't we thought about making the util package also an
independent or separate package though, because the code has also been
copied over to bhmm?

**Comment by franknoe** [comment]
True. The point was that this isn't really msmtools stuff, so it would
rather be a separate package, but then we would need a converged API, but
we keep changing things here. So I feel this would create many more
headaches to introduce a dependency to another package at this point.

**Comment by marscher** [comment]
Am 27.11.2015 um 15:07 schrieb Frank Noe:

> True. The point was that this isn't really msmtools stuff, so it would
> rather be a separate package, but then we would need a converged API, but
> we keep changing things here. So I feel this would create many more
> headaches to introduce a dependency to another package at this point.
> 
> Honestly, why do we need a "stable" API for programmer/math/etc utilities?

I'll suggest to create a repo only containing the util package at root 
level, so we can include it via git subtrees in all dependent projects.

A subtree is a merge of all the commits in a different repo into the 
main repository under a given directory. This way we can easily share 
the same code base for all projects using the util package.

Further reading:
https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging

This will actually not change the way we use util, but just the way we 
maintain it (avoid copy paste code for instance).

If desired, I can set this up.

**Comment by franknoe** [comment]
OK, that sounds fine for me.

**Comment by trendelkampschroer** [comment]
Hi, that sounds like a very sophisticated way to solve our problem and I like it better than maintaining duplicate code. Thanks @marscher for researching this.

I have one reservation however. If we maintain a single util package that will be a subtree of both msmtools and pyemma, than a user who wants to install msmtools, will need to install everyhing in the util package. It means also that he will need to have all dependencies for the pure pyemma-part of utils.

As an example consider the following: Some developer comes up with cool functionality for pyemma that depends on mdtraj, but it will be a potentially very useful utility for a number of pyemma submodules. If we maintain a joint util package we have two options: a) Put mdtraj as a dependency for util b) Put another util_pyemma module into pyemma to avoid dragging in extra dependencies into util.

From a developers point of view I think it would also help to have a util package in msmtools and in pyemma. If I want to develop a utility feature for pyemma I can use all functionality available via pyemma or its dependencies, if we have a common util package than I might accidentally drag in an extra dependency for msmtools while that util was never meant to be used from within msmtools.

Since msmtools is a pyemma dependency anyway the opposite case is no problem. I can use all msmtools.utils from pyemma and developing for msmtools I can put whatever I want into msmtools.util, because functions with duplicate names will reside in different namespaces, i.e. pyemma.util and msmtools.util. 

Since msmtools.util will very probably change a lot slower than pyemma.util I don't think we will have to worry about the duplicate creation of new functionality for the same thing in pyemma and msmtools. I'd rather expect that pyemma.util will grow a lot faster and include functionality that is not relevant for msmtools.

I don't know if it would be very difficult to determine which part of util is exclusively used by pyemma and which is used either by msmtools only or by both, but I think it would be worth to consider this approach. 

What do you think?

**Comment by franknoe** [comment]
I think defining a common util or util/base function is straightforward.
Utility functions depending on mdtraj should be in pyemma.coordinates, 
pyemma.util and msmtools.util should only be very basic stuff depending at
most on native python packages and numpy. Another package that would
benefit from this treatment is the _base package. That way we could have
Estimators and Models in several packages simultaneously.

But thinking about it, I have some related reservations. Subtrees is
another special effect making development more complicated than just
having files in the package. If we change the behavior of the util
subtree, it will still break all packages that use the util subtree (not
the releases, but the devel versions. So someone will have then to
fix/adapt the codes, and the person changing the subtree code might not
even be aware of the packages using it). As long as it's just files, each
package is self-consistent and easy to refactor without secondary effects.
Only at the point when we decide to package util out we have to make the
effort of making all packages using it consistent (and since util are
usually small independent functions rather than complex code this should
be easy). So I don't think that at this stage having copied util code is
too bad. How often did this really cause a problem or significant extra
work?

I already find the ipython-notebook treatment (which I guess uses a
similar principle) difficult to work with, and I am a bit worried that we
might end up in a situation where only Martin can set up things and
develop. More sophisticated is not always better for everyone.

Just my thoughts. If you think this is paranoid and it's totally easy, I'm
happy to give it a try, but generally my feeling is that we should rather
try to find ways to make the overall setup and maintainance effort less
rather than more.

**Comment by marscher** [comment]
would require too technical solutions.
