### ISSUE TITLE
[refactor transformer] used-defined mean is ignored

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/PyEMMA#679]
It seems that we have lost the ability to give a user defined mean to the TICA transformer. Not subtracting the mean is not possible either...
https://github.com/markovmodel/PyEMMA/blob/devel_refactor_transformer/pyemma/coordinates/transform/tica.py#L229

**Comment by marscher** [comment]
We need to integrate this in covartools. Happy to receive a PR for that...

**Comment by fabian-paul** [comment]
Well we could just add the functionality directly to the TICA estimator. Substracting the user-defined mean from the chunks, just like in the old times. But I would like to hear @franknoe's opinion on this first.

**Comment by franknoe** [comment]
If you want to maximize efficiency, substraction of the mean, copying or 
typechange of the inputs and calculation of the covariance matrix are 
entagled. If you build it into PyEMMA, chances are e.g. that you are 
copying all data twice in some cases. This case handling is why the code 
in covartools comparatively complicated. So the best solution would be 
to add an option to subtract a given mean there. I think that's not too 
hard, it just must be passed through the functions and used instead of 
the calculated mean.

The option to not subtract a mean at all is already there in covartools, 
this just needs to be used.

Am 29/01/16 um 10:59 schrieb fabian-paul:

> Well we could just add the functionality directly to the TICA 
> estimator. Substracting the user-defined mean from the chunks, just 
> like in the old times. But I would like to hear @franknoe 
> https://github.com/franknoe's opinion on this first.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/679#issuecomment-176674463.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
We (@fabian-paul and @fnueske) agreed upon exposing the "remove_mean" flag of covartools in TICA API to have avoid removing the mean (which is useful in case of variational principle). Will add an PR to deal with this.
