### ISSUE TITLE
Error/missing documentation in periodic boundary option for distance calculation

### ISSUE THREAD

**Issue by nsplattner** [markovmodel/PyEMMA#732]
It is unclear if and how  periodic boundary options are used for minimum distances in the functions

add_residue_mindist()
add_group_mindist()

For all other distances, periodic=True is the default. For minimum distances this option is not available, but a correction for periodic boundaries is effectively done when calculating the distances and it is completely unclear where the information about the periodic box is taken from.

In general I suggest to change the default for all distances to periodic=False since a correction for periodic boundaries should only be done when the user explicitely provides information about the unitcell or indicates where it should be taken from.

**Comment by gph82** [comment]
Right, now I see that e.g in add_inverse_distances the argument periodic=True does not even get parsed ... I'll correct that, thanks!

**Comment by gph82** [comment]
Couple of ideas:
- add_residue_mindist() calls ResidueMinDistanceFeature wich calls mdtraj.compute_contacts which itself (outside of pyemma) calls mdtraj.compute_distances **without** periodic=False:
  https://github.com/mdtraj/mdtraj/blob/master/mdtraj/geometry/contact.py#L160 and https://github.com/mdtraj/mdtraj/blob/master/mdtraj/geometry/contact.py#L180 ... so we cannot do anything (easily) here for the moment.
- add_group_mindist() calls GroupMinDistanceFeature which calls  mdtraj.compute_distances directly (=within PyEMMA), so there we can do what you suggest and parse periodic=periodic

As to what the default value should by (on the PyEMMA side)...I see your point about having more control over when to correct for pbc...but still find it more natural to leave it to True, and let mdtraj handle the cases in which no cell information is there. I'm assuming that mdtraj simply overrides this when no cell info is there, at least from this behavior:

``` python
geom = md.load('test_no_CRYST.pdb')
print(geom.unitcell_lengths)
md.compute_distances(geom, [[0,1]])
## None
###array([[ 0.38407165]], dtype=float32)
```

what do you think? 

On a related note, I think @franknoe wants some refactoring of the distance featurization at some point, so it might be a good moment to start talking about this

**Comment by franknoe** [comment]
Yes, this needs to be documented.

The problem is, it's not so clear in your example how to do this right. 
My suspicion is that your trajectories do have unitcell information. You 
can test this by

``` python
     import mdtraj
     traj = mdtraj.load('your.xtc', top='your.pdb')
     print traj.unitcell_lengths
```

If the result seems to make sense, you do have unitcell information, so 
implicitly you did specify the unitcell. If at the same time, the 
trajectories have been unwrapped in some way (VMD? ACEMD output?), then 
the trajectory information is inconsistent and the problem is already in 
the input.

If this is the case, then the real question is how to deal with an 
inconsistent input:
- We could detect (upon any trajectory loading) if periodic boundaries 
  are given, but coordinates are outside the boundaries. In this case, 
  warn the user that there is pbc information while the data is outside 
  the box.
- If this situation occurs in a distance calculation (or if distances < 
  0.1 nm occur, which is clearly unphysical, but I would favor catching 
  this at the box level), switch to periodic=False, but warn the user.

Generally, the default is periodic=True because we simply pass this call 
on to mdtraj, which also has periodic=True as a default. So mdtraj 
should report exactly the same distances. I think this default makes 
sense (pbc information must be taken from the trajectory - you can't ask 
the user to supply it separately because if simulation volume is not 
constant, the pbc information changes in time). Only if really no box is 
given, the argument should be ignored.

Am 17/03/16 um 12:18 schrieb nsplattner:

> It is unclear if and how periodic boundary options are used for 
> minimum distances in the functions
> 
> add_residue_mindist()
> add_group_mindist()
> 
> For all other distances, periodic=True is the default. For minimum 
> distances this option is not available, but a correction for periodic 
> boundaries is effectively done when calculating the distances and it 
> is completely unclear where the information about the periodic box is 
> taken from.
> 
> In general I suggest to change the default for all distances to 
> periodic=False since a correction for periodic boundaries should only 
> be done when the user explicitely provides information about the 
> unitcell or indicates where it should be taken from.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/732

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Just looked it up. geom as an object "_have_unitcell" that is checked for when mdtraj internally computes distances. If it's not there, it just calls a distance function that does what @nsplattner wants. 
From https://github.com/mdtraj/mdtraj/blob/master/mdtraj/geometry/distance.py#L74 

``` python
 if periodic and traj._have_unitcell
```

else it just calls:

``` python
def _distance(xyz, pairs):
    "Distance between pairs of points in each frame"
    delta = np.diff(xyz[:, pairs], axis=2)[:, :, 0]
    return (delta ** 2.).sum(-1) ** 0.5
```

**Comment by gph82** [comment]
"\* We could detect (upon any trajectory loading) if periodic boundaries are given, but coordinates are outside the boundaries. In this case, warn the user that there is pbc information while the data is outside the box." 
even if all data is inside the box, you might want to use PBC for the minimum image convention, in case the molecule is split across one wall, right?

**Comment by franknoe** [comment]
Yes, this case is fine. What I wrote is that when pbc information is given but data is outside the periodic cell, this is an indication of inconsistent trajectory information.

**Comment by nsplattner** [comment]
If we leave periodic=True it should be well documented and with options to disable it or manually provide unit cell information. With 'provided by the user' I also mean that the user could have an option like pbc='trajectory' for reading the unit cell information from the trajectory. 

Post-processed trajectories are not an exception but commonly used since usually we just look at the protein and not the whole proten+waterbox system. The PBC information is handled differently by different programs and post-processing tools, so this really needs to be handled carefully.

**Comment by gph82** [comment]
What do you think of something like #734 ?

**Comment by franknoe** [comment]
Am 17/03/16 um 14:54 schrieb nsplattner:

> If we leave periodic=True it should be well documented and with 
> options to disable it or manually provide unit cell information. With 
> 'provided by the user' I also mean that the user could have an option 
> like pbc='trajectory' for reading the unit cell information from the 
> trajectory.
> 
> Post-processed trajectories are not an exception but commonly used 
> since usually we just look at the protein and not the whole 
> proten+waterbox system. The PBC information is handled differently by 
> different programs and post-processing tools, so this really needs to 
> be handled carefully.
> 
> I know, this is why I suggest to check for inconsistent input. Did you 
> check if you have pbc information in the xtcs?

@gph82: Since `mdtraj.compute_contacts` has no `periodic` 
option, we can't fix it at the analysis level. If the above check is 
positive (pbc information given, but trajectory unwrapped), can you open 
an issue there to discuss the problem of using an unwrapped trajectory 
with pbc information as an input? Perhaps they have a suggestion how to 
deal with this at the reading level - if not at least a periodic option 
could be added to compute_contacts.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/732#issuecomment-197888284

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by nsplattner** [comment]
I think in my case the PBC information is in the dcds. I have now disabled the periodic-option in my source code and then the calculation is correct. So its really a wrong or double information in the post-processed trajectory provided by VMD.

@gph82 Maybe it would be good to add an explicit warning for this to your documentation something like 
periodic=True may fail for post-processed trajectories

**Comment by franknoe** [comment]
Am 17/03/16 um 15:09 schrieb nsplattner:

> I think in my case the PBC information is in the dcds. I have now 
> disabled the periodic-option in my source code and then the 
> calculation is correct. So its really a wrong or double information in 
> the post-processed trajectory provided by VMD.
> 
> Thanks! In this case, I suggest to discuss this issue in mdtraj, because 
> they will run into the same problems. Nuria: can you provide a minimal 
> example (e.g. a pdb plus a 1-2 frame long subtrajecty where this problem 
> occurs) in order to run the issue?
> 
> @gph82 https://github.com/gph82 Maybe it would be good to add an 
> explicit warning for this to your documentation something like
> periodic=True may fail for post-processed trajectories
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/732#issuecomment-197893920

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by nsplattner** [comment]
o.k., I prepare some test files.

**Comment by gph82** [comment]
https://github.com/mdtraj/mdtraj/issues/787#issuecomment-197900985

**Comment by marscher** [comment]
handled by #734
