### ISSUE TITLE
CKtest/reversible estimator NotConvergedWarning

### ISSUE THREAD

**Issue by thempel** [markovmodel/PyEMMA#736]
It would be nice if we could pass the maxiter/maxerr arguments from the bayesian_markov_model.cktest() to the reversible transition matrix estimator because in some cases, I keep getting a _NotConvergedWarning: Reversible transition matrix estimation didn't converge._

**Comment by fabian-paul** [comment]
Hi @thempel 
does the CK-work still work, even when you get these warnings?
As a general comment about accessing optional parameters of msmtools via Pyemma: I think this kind of problem happens in many places. In principle every api function should have **kwargs because the user could have set a parameter that is meant to be passed to the lower layers. But in practice we rely on default values in many places. I think we have to come up with a general solution for this.

**Comment by thempel** [comment]
Yes, the test still works but the question is if the result is meaningful or not... I agree, a general solution with **kwargs would be best.

**Comment by fabian-paul** [comment]
i think this is the place where the parameters are not passed on:
https://github.com/markovmodel/PyEMMA/blob/ace854749621368e47377893cedbd7b10864e9a8/pyemma/msm/estimators/bayesian_msm.py#L133
[edit]... because the parameters can't even be set by the user.

**Comment by fabian-paul** [comment]
Well **kwargs isn't the only solution. I can think of solving this with a context manager and thread-global variables.
Or we could even abstract options as classes. Then there could be nested options (e.g. MLMSM has it own options and one of them is a package of options that gets passed to msmtools' estimators.)

**Comment by fabian-paul** [comment]
@thempel  For the time being, i suggest that you estimate a maximum likelihood MSM (errors=None?) and do the CK-test there. The maximum likelihood MSM  allows you to set maxiter, which is respected by the Chapman-Kolmogorov class.

**Comment by franknoe** [comment]
You can set whatever you want if you use the Object access, i.e. 
construct a MaximumLikelihoodMSM or BayesianMSM with your favorite 
parameters, pass it to ImpliedTimescales, and run an `estimate`. 
That's what the `timescales_msm` api function does.

The api functions were meant as convience access, and thus we tried not 
to overload them with parameters to avoid confusion of how to use this 
function. A solution with **kwargs would be acceptable, because expert 
users can optionally descent in that.

Am 18/03/16 um 10:48 schrieb fabian-paul:

> @thempel https://github.com/thempel For the time being, i suggest 
> that you estimate a maximum likelihood MSM (errors=None?) and to the 
> CK-test there. The maximum likelihood MSM allows you to set maxiter, 
> which is respected by the Chapman-Kolmogorov class.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/736#issuecomment-198283973

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
This one does not seem to be urgent enough for someone to impl this kwargs feature. But as Frank said, one can set this, if one uses the Estimator object directly.
