### ISSUE TITLE
Kmeans unnecessary copies during clustering phase.

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#769]
Already discussed with @clonker so far:
ping @franknoe 
1. We can add the possibility to pass an Iterable to the C-extension, so it would not matter how large the data is. There would be no need for copies, but there exists some cases where it will be horrible inefficient (eg. costly features will be re-calculated for every iteration). For the inefficient cases we could show a warning, but it will work.
2. Restrict to DataInMemory as input for kmeans (mini-batch-kmeans is suited for the case of large data-sets). For this case DataInMemory needs to ensure that all arrays are c-contigous.

**Comment by franknoe** [comment]
Since kmeans may need many iterations, I think it's OK to force that 
data are in memory once the algorithm is performed. However, I don't 
think it's necessary to force the input to be a DataInMemory Reader. I 
think the issue can be restricted to the following:
1. If the input _is_ DataInMemory, just get a reference to the data (no 
   need to copy)
2. If not, try to create a copy, and raise an exception if unsuccessful 
   (current behavior)

So the only change would be to add option 1.

Am 11/04/16 um 15:27 schrieb Martin K. Scherer:

> Already discussed with @clonker https://github.com/clonker so far:
> ping @franknoe https://github.com/franknoe
> 
> 1.
> 
> ```
> We can add the possibility to pass an Iterable to the C-extension,
> so it would not matter how large the data is. There would be no
> need for copies, but there exists some cases where it will be
> horrible inefficient (eg. costly features will be re-calculated
> for every iteration). For the inefficient cases we could show a
> warning, but it will work.
> ```
> 
> 2.
> 
> ```
> Restrict to DataInMemory as input for kmeans (mini-batch-kmeans is
> suited for the case of large data-sets). For this case
> DataInMemory needs to ensure that all arrays are c-contigous.
> ```
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/769

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
1. is an optimization which we should definitely add. Probably we had this on our list, but it got lost.

**Comment by marscher** [comment]
For this to work the c-code needs to be adopted to take a list of contiguous c-arrays. Currently it only supports one large chunk - this is why we are making a copy.

The optimized cases will then include DataInMemory and DataSource.in_memory=True.

**Comment by marscher** [comment]
With the new pybind interface, this one should be very easy to implement.
