### ISSUE TITLE
tram documentation

### ISSUE THREAD

**Issue by cclementi** [markovmodel/PyEMMA#818]
Hi, this is related to issue I opened earlier (#817, now closed). I see that the online documentation has been updated to include version 2.2 (with tram). However, if you look for instance at the documentation for the function pyemma.thermo.estimate_umbrella_sampling (see http://www.emma-project.org/v2.2/api/generated/thermo-api/pyemma.thermo.estimate_umbrella_sampling.html#pyemma.thermo.estimate_umbrella_sampling), it says:

Returns:  
estimator_obj – The requested estimator/model object, i.e., WHAM, DTRAM or TRAM. If multiple lag times are given, a list of objects is returned (one MEMM per lag time).

Return type:  
MEMM or list of MEMMs

It would be useful to have a link to the page where the MEMM class is documented so that one can easily find the attributes of the estimator_obj. 

Thanks!

**Comment by franknoe** [comment]
+1. Also the MEMM documention is not really revealing. I think if you 
have an MEMM, the models will be MSMs, won't they? - so that should be 
linked too.
 From estimation_umbrella_sampling you could get a MEMM or a 
StationaryModel, depending on which estimator is used, so that would 
need to be distinguished in the docs.

Am 31/05/16 um 17:36 schrieb Cecilia Clementi:

> Hi, this is related to issue I opened earlier (#817 
> https://github.com/markovmodel/PyEMMA/issues/817, now closed). I see 
> that the online documentation has been updated to include version 2.2 
> (with tram). However, if you look for instance at the documentation 
> for the function pyemma.thermo.estimate_umbrella_sampling (see 
> http://www.emma-project.org/v2.2/api/generated/thermo-api/pyemma.thermo.estimate_umbrella_sampling.html#pyemma.thermo.estimate_umbrella_sampling), 
> it says:
> 
> Returns:
> 
> estimator_obj – The requested estimator/model object, i.e., WHAM, 
> DTRAM or TRAM. If multiple lag times are given, a list of objects is 
> returned (one MEMM per lag time).
> 
> Return type:
> 
> MEMM or list of MEMMs
> 
> It would be useful to have a link to the page where the MEMM class is 
> documented so that one can easily find the attributes of the 
> estimator_obj.
> 
> Thanks!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/818, or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQlsjmbC33gpWIOjsG-pBId0-55Jwks5qHFWRgaJpZM4IqqhF.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Actually, the models attribute doesn't even appear in the documentation. I think we could solve that by defining a getter and setter for the property `models` (we need both, otherwise we just mask the attribute and can't write to it anymore) and documenting the getter.
