### ISSUE TITLE
parameters for tram

### ISSUE THREAD

**Issue by juanmit** [markovmodel/PyEMMA#836]
Hi, I am a new user of PyEMMA, and trying to apply tram estimator onto my projects. However, I am feeling really confused about the parameters for the tram analysis.

X : tuple of (ttrajs, dtrajs, btrajs)

Here is my understanding of each element.

ttrajs are the index of the frames. Assuming each traj has 5 frames so ttrajs=[[0,1,2,3,4],[0,1,2,3,4]]
dtrajs are the index of Markov State(assuming 4 state model) so dtrajs=[[0,0,1,2,3],[1,2,1,2,0]]
but I dont know what is btrajs assuming I have two independent simulations with k=0 and k=1. Could you help me to understand this value? 

Thanks a lot.

**Comment by cwehmeyer** [comment]
Hi and welcome to PyEMMA!

First, I would recommend to use the `pyemma.thermo.tram` API function instead of the class; is is usually much more convenient. This function also requires you to provide `ttrajs`, `dtrajs`, and `bias` (`btrajs` when you use that class), as well as the lagtime parameter `lag`.

`ttrajs` is (like `dtrajs`) a list of discrete trajectories. The elements do not number the frames, but indicate under which thermodynamic conditions the frames were created. In your example of two independent simulations at k=0 and k=1, you would get

``` python
ttrajs = [[0, 0, 0, 0, 0], [1, 1, 1, 1, 1]]
```

Your understanding of `dtrajs` is correct: this parameter is a list of discrete trajectories which indicate the configuration states of the frames.

The `bias` (or `btrajs`) parameter refers to the bias energies of the frames in all the different thermodynamic states. That means, for each trajectory with n frames, you have to provide a (n,m) matrix of bias energies, where m is the number of thermodynamic states; in your case, m=2. The row index refers to the frames, the second index to the thermodynamic state.

**Comment by juanmit** [comment]
Thanks a lot. That 's really really helpful. I will spend more time on tram to see how further I can get. 

--Hongbin
