### ISSUE TITLE
How to track the info of each state after TRAM?

### ISSUE THREAD

**Issue by juanmit** [markovmodel/PyEMMA#888]
Hi PyEMMA,

I am recently running TRAM on my simulation data, and the simulation data had been clustered into 250 states. However, after running TRAM, the output of the stationary population only shows populations of 244 states, which 6 states are missing. Does it mean these 6 states have negligible population?  And how to find which population is for which state?  Thanks for helping.

BTW, how big effect on the values of init_maxerr and maxerr? Since I have a large set of data, are there any ways to speed up TRAM analysis? Thanks!!!!!

--Hongbin

**Comment by fabian-paul** [comment]
Hi Hongbin,

you can map back the stationary distribution of the TRAM estimator using the property `active_set`.
Suppose that you have the tram object 

``` Python
tram = pyemma.thermo.TRAM(lag=your_lag)
tram.estimate((ttrajs, dtrajs, btrajs))
```

Then you can show the active set and bring the stationary vector to the shape 250 by doing:

``` Python
print 'For these states, TRAM could estimate stationary information', tram.active_set
pi_full = np.zeros(tram.nstates_full)
pi_full[tram.active_set] = tram.stationary_distribution
```

We are currently working on a feature that will make this transformation more user-friendly.

This is slightly hackish because here I assumed that the states outside the active set have zero probability. In reality the stationary probability of these states in undefined.

You can have states outside the active set if these states are not connected reversibly to the rest of the data, that is there are trajectories that enter the state, but no trajectory leaves the state. Or the other way around. That's why the stationary vector is undefined for these states.
It is kind of tricky to reliably determine the connectivity of the simulation data in the framework of MSMs. In TRAM there is also the overlap of Boltzmann distributions of different ensemble which goes into the determination of the connected set. This is documented in the docstrings of the cset module, https://github.com/markovmodel/thermotools/blob/devel/thermotools/cset.py
Please keep in mind that TRAM's calculation of the connected set is only approximate and the set of states that are really connected might be smaller than indicated by TRAM.

We have not really investigated the effects of init_maxerr and maxerr. init_maxerr controls the error of an initial MBAR run that is used to initialized the TRAM iterations. When the data is very far from equilibrium, I guess that the MBAR step will not help much and you could use a very large value of init_maxerr, like 0.1.
We have noted that TRAM can converge extremely slow if the connectivity of the data is very bad. As I wrote, the connectivity of the data can currently only be determined approximately. So there is a chance that the connectivity is indeed very low but this isn't detected by TRAM's heuristics. Please try to change the connectivity heuristic to `connectivity='post_hoc_RE'`, i.e. when intializing TRAM:

``` Python
tram = pyemma.thermo.TRAM(lag=your_lag, connectivity='post_hoc_RE')
```

From our experiences that can prevent extreme slowdown of the convergence.

To further speed up TRAM, you can switch from the log-space implementation of TRAM to the direct space implementation by initializing with direct_space=True. However this is only recommended if the spread in bias energies is small like in Umbrella sampling. For multi-temperature simulations of solvated systems this in not recommended. Moreover the direct space implementation can be accelerated by initializing with N_dtram_accelerations=10 This interleaves the TRAM iteration with a dTRAM-like step which can speed-up convergence. Currently this is only implemented for the direct space version but could be added easily to the log-space version. We would appreciate your contribution to TRAM ;-)

Best,
Fabian

**Comment by juanmit** [comment]
Thanks a lot!!!!! I appreciate your help!!!!! It works well for me now.  I think you are right about the slowness due to "not-reach-equilibrium" simulation data.  Initially, the toy model was really fast for me, but it is super slow for my large protein systems(not sure if it needs more simulation data or not).
And I do not think I can use post_hoc_RE to speed up my research since my simulation data is at different Temperatures.   Thanks a lot !!!!!

--Hongbin

**Comment by fabian-paul** [comment]
Hi Hongbin,

I guess that there is some misunderstanding here. You CAN use connectivity='post_hoc_RE' for data that comes from multi-temperature simulations. I would even recommend it.
But you should rather not use direct_space=True.

Best,
Fabian

**Comment by juanmit** [comment]
Hi Fabian,

Thanks a lot for the notation. I really appreciate your notation!!!

I did not use connectivity='post_hoc_RE' initially because I was thinking that calculating all_assumed_overlap( summed_count_matrix) would be more accurate, and also I misunderstood the concepts of post_hoc_RE and direct_space.  Since my simulation data is at different temperatures and restraints, I will try to apply post_hoc_RE to my simulation data. 

BTW, I am digging another question these days, where the approximate stationary population from TRAM shows a high-population state that never sampled in the reference ensemble. In other words, I calculated the reduced potential by setting up a reference ensemble(lets say at thermo state 300K and 0.5 restraint) and apply TRAM, the output shows a high population state(lets say state 5). After checking the simulation data,  thermo state with 300K and 0.5 restraint never sampled state 5. Here I have two concerns:
1. If my data is far from equilibrium, does it mean that TRAM predicts a "theoretical-good" state  from the calculation from the bad overlap?
2. If my data is in equilibrium, is it necessary for TRAM to predict a high-population state that sampled in the reference condition? 

--Hongbin
