### ISSUE TITLE
Complications when operating on a trajectory file which is being written to

### ISSUE THREAD

**Issue by maxentile** [markovmodel/PyEMMA#892]
Hi!

Sometimes trajectory files are being written to at the same time as PyEMMA is running, and we would like to use PyEMMA to analyze the data as it arrives. This has caused a couple errors, which can be avoided by copying the trajectories to a "staging" folder where nothing is changing.

Tagging @sonyahanson and @jchodera .

Error  1: `kmeans.get_output()` is assigning some frames the label -1, at the end of the trajectory
This is causing MSM estimation to fail, since not all discrete state labels are nonnegative.

```
kmeans = pyemma.coordinates.cluster_mini_batch_kmeans(Y, k = n_clusters, max_iter = 1000)
dtrajs = [dtraj.flatten() for dtraj in kmeans.get_output()]
```

```
    self._model = self._estimate(X)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_msm.py", line 220, in _estimate
    dtrajstats = _DiscreteTrajectoryStats(dtrajs)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/msm/estimators/_dtraj_stats.py", line 47, in __init__
    self._hist = msmest.count_states(self._dtrajs)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/msmtools-1.1-py2.7-linux-x86_64.egg/msmtools/estimation/api.py", line 104, in count_states
    return _count_states(dtrajs)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/msmtools-1.1-py2.7-linux-x86_64.egg/msmtools/dtraj/api.py", line 330, in count_states
    bc = np.bincount(dtraj)
ValueError: The first argument of bincount must be non-negative
```

Error 2: index error when calling `coordinates.save_traj` / accessing trajectory frames

Here, I think the problem is that we had created two sources: one that only reads the coordinates needed by our featurizer  (`source = pyemma.coordinates.source(fnames, features = feat)`), and another one (hours later), after MSM estimation has completed, which contains all of the coordinates: `source_full = pyemma.coordinates.source(fnames, top = top)`, for when we are writing out PDB files of configurations sampled from each state. Should we just make sure the definition of `source_full` occurs at ~the same time as the definition of `source`?

```
pyemma.coordinates.save_traj(source, samples[i], '{0}_state_{1}.pdb'.format(project_name, i))
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/api.py", line 658, in save_traj
    traj = frames_from_files(trajfiles, top, indexes, chunksize, stride, reader=reader)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/data/util/frames_from_file.py", line 111, in frames_from_files
    length))
ValueError: largest specified index (487 * stride=487 * 1=487) is larger than trajectory length '/cbio/jclab/projects/fah/fah-data/munged3/no-solvent/11406/run8-clone35.h5' = 320
```

**Comment by marscher** [comment]
Hi,

reading from a file which is currently under change is totally
unreliable in general. You do not know when a buffer has been finally
written by the operating system eg. when it arrives the file system.
Unless you have a file format which supports it (I'd guess hdf5 for
parallel file systems might support it)l, this mode will most likely
brake everything.

So both errors you observe are due to breaking the following assumption
we made:

PyEMMA will use the information of trajectory lengths when it will first
encounter the file. If the file has changed (a new reader is
constructed), it will check for this situation and query that
information again.

So your workaround of moving completed trajs to the staging folder is
the best solution here.

We could think of implementing this for a sane file format, but in
general this is a use case we can not implement due to file
format/operating system issues.

**Comment by jchodera** [comment]
Thanks for the quick response!

Two comments:
1. I believe these errors in particular persisted even when the data was
   staged. Can you confirm @maxentile?
2. Are there formats you would consider "more sane"? If we want to be able
   to adaptively build MSMs, we would ideally figure out some sort of solution
   aside from staging. If the behavior is simply that the file may get longer
   as more data is added, are there formats we can trust to be able to analyze
   the portion corresponding to the number of snapshots available when the
   file was first encountered? Alternatively, are there trajectory database
   formats we could move to that would solve this problem?

**Comment by maxentile** [comment]
Thanks so much, Martin!
1. Hmm, I believe data-staging actually eliminated these two errors. @sonyahanson , is that correct? (I believe [this other error](https://github.com/markovmodel/PyEMMA/issues/891) is one that may have persisted even when the data was staged.)
2. Martin mentioned HDF5 as a format that could support concurrent read/write file access, and our trajectories are currently stored in the HDF5 format.

**Comment by marscher** [comment]
I think of a solution right now.
@clonker could we change the trajectory_length attribute that way, that it will back propagate to the final source, which will os.stat the underlying files again to find a proper length (if the file format supports it). The underlying iterators would then have to obtain the length every time from the reader. I'm not sure we've done this? An iterator would then know this information and algorithms will hopefully just use more data per iteration...  :sunglasses:

So I'd guess that this could be implemented for certain formats, but I'd really doubt that we could reliably do this in general.
...
Gromacs TNG could maybe also be able to handle this, since it is also a chunked format.

**Comment by clonker** [comment]
Sure, we ask all the parent estimators about the trajectory length.. so except for the os.stat part the infrastructure is there.
I'm just not sure how well it is going to behave..

**Comment by jchodera** [comment]
This sounds like a good idea!

**Comment by sonyahanson** [comment]
Yes, data-staging eliminated these errors as far as I can tell.
