### ISSUE TITLE
[kmeans] parallelize distance calcuation during clustering phase 

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#893]
So far, we've only implemented this for the cluster assignment phase.

**Comment by jchodera** [comment]
Isn't the parallel cluster assignment used in the clustering iteration process? Is it just the generator update that isn't parallelized?

**Comment by marscher** [comment]
No it is only used during assignment. We need to create an abstract function, which will wrap all distance calculations loops and do a reduction on the minimum distance.

**Comment by rafwiewiora** [comment]
Hi guys,

Just want to confirm that it is still the case that only the cluster assignment is parallelized, but not the k-means iterations? 

I'm asking because I've hit ridiculous ETA's for a 10M frames, 4.5k TICs dataset, I want to k-means into 100, 500, 1k, 2k, 3k, 4k, 5k clusters. Only 100 and 500 managed to get through the `k-means++` initialization, but 1k clusters already was saying 6 days ETA to even finish initialization. So we decided to set a `stride=10`, but this puts us at pretty high ETAs for initialization already still, so not sure how long the iterations will then take:

```
initialize kmeans++ centers:  40% ( 803/2000) [######           ] eta 19:33:11
initialize kmeans++ centers:  23% ( 715/3000) [####             ] eta 39:36:54
initialize kmeans++ centers:  19% ( 766/4000) [###              ] eta 54:13:43
initialize kmeans++ centers:  15% ( 762/5000) [##               ] eta 62:56:32
```

Not sure we can go for a higher stride here (at 5k clusters, stride 10, we have only 200 samples / cluster center), so this is not looking good.

Is there some more parallelization here that I'm missing (I set the `'OMP_NUM_THREADS'`, everything here running at 16 threads)? If not, then adding more parallelization would be a much desired feature, we're just going to have more and more data going forward...

(cc @jchodera)

**Comment by marscher** [comment]
You're are right, as quoted previously this is not parallel. I think I could add it with #1142

**Comment by rafwiewiora** [comment]
Ok, thanks! @maxentile has been looking into a quick fix for the parallelization

**Comment by jchodera** [comment]
@marscher : It would be awesome if you could add parallelization in #1142! It looks like you'd just want to add the OMP directives found [here](https://github.com/markovmodel/PyEMMA/pull/1142/files#diff-f4f46a1908a87225e197bde5960d9281R57) for assignment to similar locations around [here](https://github.com/markovmodel/PyEMMA/pull/1142/files#diff-f110a7e972d5c167ea17501192b79023R51) for clustering. There may also be a way to reuse your already-parallel assignment code, but it may not be set up to handle the same kind of chunking scheme you use for clustering.

**Comment by marscher** [comment]
The suggested pattern adds actually more overhead, than it helps
speeding things up.

I can push the stuff I already have and let you OpenMP experts have a
look? You can also open PRs against forks :)

**Comment by marscher** [comment]
My test system didn't have enough dimensions, with like 100 dimensions
it starts to scale, but still not very satisfying.

**Comment by jchodera** [comment]
> My test system didn't have enough dimensions, with like 100 dimensions
it starts to scale, but still not very satisfying.

Our use case has 5000 dimensions, but aren't you parallelizing across *configurations* rather than dimensions?

**Comment by marscher** [comment]
you're right, it should scale with n_clusters.

**Comment by marscher** [comment]
Okay now it is significantly faster for my test system (even the small
one). The results look good (visual inspection), however there is one
test failure related to random seeding (probably this does not work as
expected in a multi-threaded environment).

**Comment by marscher** [comment]
I'd be happy on any feedback on the openmp stuff.

**Comment by marscher** [comment]
done in #1142

**Comment by jchodera** [comment]
Thanks again!
