### ISSUE TITLE
arguments target/orgin are swapped in ReactiveFlux.mfpt and msm.analysis.mfpt

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#90]

**Comment by franknoe** [comment]
I guess the reason is that target is mandatory while origin is optional 
for an mfpt calculation. It would be nicer to have mfpt(origin, target), 
but I'm not sure how to do this.

Am 25/02/15 um 14:22 schrieb Martin K. Scherer:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/90>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by trendelkampschroer** [comment]
As franknoe pointed out this is not possible since target is mandatory while origin is optional.

**Comment by marscher** [comment]
trick is then to assign target also a default value (maybe -1), so the arguments can be swapped. If target is not provided, raise an exception.

**Comment by franknoe** [comment]
If both are kwargs there is no order.

I have no strong feeling about this.

Am 25/02/15 um 14:50 schrieb Martin K. Scherer:
>
> trick is then to assign target also a default value (maybe -1), so the 
> arguments can be swapped. If target is not provided, raise an exception.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/90#issuecomment-75962257>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
I suggest to leave this as it is, because it's low level API.

In the new high-level MSM api (i.e. in the MSM object) we don't have this problem anymore. It is simply 
mfpt(A, B)
